# -*- coding: utf-8 -*-
# Writer (c) 2017, Vorotilin D.V., E-mail: dvor85@mail.ru

NAME2LOGO = {
    "mtv live hd": "http://torrent-tv.ru/uploads/WjyYXtYHhG5COxGab7luHb1bmvAioA.png",
    "euronews": "http://torrent-tv.ru/uploads/Vb3fP5gUK0q40WuzYeUhMT7RQmDg27.png",
    "русская комедия": "http://torrent-tv.ru/uploads/4Q3vGcJh5o0cgJB18scb90ogvL6OYV.png",
    "da vinci learning": "http://torrent-tv.ru/uploads/Yl6p1IDDkZxxiUa3p2JxI66mIlOPns.png",
    "тбн": "http://torrent-tv.ru/uploads/r9O7HmwQbFR4oKMH9yKAogE8xBzwz4.png",
    "кхл hd": "http://torrent-tv.ru/uploads/kRN7BwVtcdaXrU4Mdg24qhFAxjx9oZ.png",
    "sct": "http://torrent-tv.ru/uploads/bDRN0guXHaNHruxtyFkpKYz8J09Xj3.png",
    "tele vsesvit": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "polsat sport news": "http://torrent-tv.ru/uploads/WhGmGGlQXEvepTfPBd3u1to4ekbtDN.png",
    "че (+7)": "http://torrent-tv.ru/uploads/fV6EjhiQaVyMMlk1era5UxYZOKX7Rf.png",
    "discovery channel hd": "http://torrent-tv.ru/uploads/SmWnYlOvkJn8GzttT2UY0vmo8PYfMg.png",
    "первый канал (евразия)": "http://torrent-tv.ru/uploads/oPB8TcSFAuJtk4hBWgAqC9yNjMpfsi.png",
    "тет": "http://torrent-tv.ru/uploads/jp0YxRwXOyMWgVfDAyQaXNwle90sV3.png",
    "нст": "http://torrent-tv.ru/uploads/fKYzdlWRz68qd9mRZnWuxMY73EyaSz.png",
    "русский бестселлер": "http://torrent-tv.ru/uploads/b5JXaosgmcanh9EVJg52yBefvdLQF7.png",
    "cgtn русский": "http://torrent-tv.ru/uploads/DcaE92lKRSDFBPlYUnsNRauFLbotKu.png",
    "revelation tv": "http://torrent-tv.ru/uploads/gK8K5dIwNW8YqrGZCilO42UX0NF03i.png",
    "точка тв": "http://torrent-tv.ru/uploads/JWwPbPnkWooIpKd5WYsdpfO3Mh14oA.png",
    "xxl": "http://torrent-tv.ru/uploads/6nJtj85PlL0MxB8RDkM3toyGND3Anc.png",
    "кубань 24 орбита": "http://torrent-tv.ru/uploads/FauvJxsKmI5a1fR62uSH9hJfHs5TCr.png",
    "nat geo wild": "http://torrent-tv.ru/uploads/ciHIDUuHEnkEuPghbcqkDQx4vadle3.png",
    "беларусь 5": "http://torrent-tv.ru/uploads/2bzJLE9Sbk9BqUBlsVrtqpsz8h0rB6.png",
    "беларусь 3": "http://torrent-tv.ru/uploads/HN5eWI5RGYxPW9BWw7mMjG1IsTSB2Y.png",
    "беларусь 1": "http://torrent-tv.ru/uploads/v5gOoahV1MZrNsZz6pCp335pW8uYHf.png",
    "pro все": "http://torrent-tv.ru/uploads/OavKhOpBMn27qPDKJXXm5rgATgovgn.png",
    "наука 2.0": "http://torrent-tv.ru/uploads/ypWbqYqKApM8cnDK1FibvQgpmgEay9.png",
    "евроновости": "http://torrent-tv.ru/uploads/2lbWxLvwTPLxkwMdCbEkZREEOTNZhU.png",
    "hustler hd": "http://torrent-tv.ru/uploads/LBz8ia8AASewVuLjMs5v4MDiVYfsJO.png",
    "bt sport 1 hd": "http://torrent-tv.ru/uploads/nTx2YNFybiRDdgyWd9TCeFXmiVfcyb.png",
    "1+1": "http://torrent-tv.ru/uploads/omm2Xc8xSVIT6Od6ca4QqMrEXw3jaK.png",
    "многосерийное тв": "http://torrent-tv.ru/uploads/4TMYdVpZYXafyIumuB5d7PrjFnslyT.png",
    "rtvi": "http://torrent-tv.ru/uploads/QBnba0xrWtpPWLL4yKDRixaCRQAmaP.png",
    "рыжий": "http://torrent-tv.ru/uploads/wfBSy60qHaPSKPpTfrNv9Q167iHIPu.png",
    "amedia hit hd": "http://torrent-tv.ru/uploads/ujYSHmxPViAzjm4yc1YPi42hju7vcq.png",
    "sextosenso": "http://torrent-tv.ru/uploads/HXMvFMLO9weHUcolVmmMKpz98T0K4K.png",
    "кубань 24": "http://torrent-tv.ru/uploads/CAAqiN96tQzFDdtz3vjrrgeIjAKqNq.png",
    "открытый мир": "http://torrent-tv.ru/uploads/aFQKX1SstzK7Pgs5D1nWqau7SwVEd9.png",
    "cgtn": "http://torrent-tv.ru/uploads/TyWVFvKwV3lOYYXWVJSj8HMu5AodJr.png",
    "renome (одесса)": "http://torrent-tv.ru/uploads/uXenrBCtSwAsv31RtOAXdn3hXm3i5N.png",
    "tmb ru": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "nova sport": "http://torrent-tv.ru/uploads/8npwMe6SAEgj5nMBCoVPCemX9fKOvI.png",
    "первый музыкальный канал": "http://torrent-tv.ru/uploads/gYpYhzD3akuKSFpRmkh2p36pXnqHoW.png",
    "zdf": "http://torrent-tv.ru/uploads/5SH5FeZiITw27CPxscjksZp272u7He.png",
    "русский экстрим hd": "http://torrent-tv.ru/uploads/upndVpIdjY3vb5vrituof5UcKISNcQ.png",
    "остросюжетное hd": "http://torrent-tv.ru/uploads/mxF7CZsqsDRMMK4pN8ekdccEgvEsZC.png",
    "etv pluss (эстония)": "http://torrent-tv.ru/uploads/cZBJJjYDyuuJHMQk3ZOogcDZYcu2SK.png",
    "news one hd": "http://torrent-tv.ru/uploads/SnaQqBa1YMS2b8b8EGdZSMCConLbDS.png",
    "fap tv lesbian": "http://torrent-tv.ru/uploads/M3LLmt76GGyLBhpAEnRtn368pAeGH3.png",
    "нтв+ кино плюс": "http://torrent-tv.ru/uploads/cnz8ZMypP2HV6phwv3rkSVQ7CgJExi.png",
    "русский иллюзион": "http://torrent-tv.ru/uploads/E9Imfr8aHN5midPVpNhJ3fo49FHbQE.png",
    "tbn europe": "http://torrent-tv.ru/uploads/bZT2NYEtReHVOSFTcW8xuDTVDvcoUn.png",
    "нтв+ инфоканал": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "наше любимое кино": "http://torrent-tv.ru/uploads/LSR5M6VxB0YDwv6803zrGFkq7vGQ3J.png",
    "galaxy tv": "http://torrent-tv.ru/uploads/pU2NsRP9CVtEgQuDTi9jcTYV8iAD4a.png",
    "наше hd": "http://torrent-tv.ru/uploads/NyV9o2C4xIMFxxYUQsS1qsdAtkqz0k.png",
    "россия ртр (украина)": "http://torrent-tv.ru/uploads/5o9OWeEw90hM5ouECuTLwj5QP8MwU3.png",
    "твц": "http://torrent-tv.ru/uploads/QEpQTskZ9hcfI0rgD8osHVYSv58pde.png",
    "blue hustler": "http://torrent-tv.ru/uploads/dFDAUzpGhQFOyHz59iyi7gsGHHMQbj.png",
    "viva de": "http://torrent-tv.ru/uploads/HagNMshKtJ7zKnk9fdmBLhITjoWdrJ.png",
    "eska rock tv hd": "http://torrent-tv.ru/uploads/VU2POxFhYCM4XhFAtOp8Y4sdlbu32M.png",
    "иллюзион+": "http://torrent-tv.ru/uploads/8LToTNvWRBHvb5IKoteKm8EwAGw8mv.png",
    "смайл-тв": "http://torrent-tv.ru/uploads/AFH2ud3ZiC5BXXPoq9OVbhCQTS0yOF.png",
    "dog tv": "http://torrent-tv.ru/uploads/NblfllG2mrqX3Zrb36rv7hLUe2sG1R.png",
    "jahonnamo": "http://torrent-tv.ru/uploads/OqNuJdvRTdBh5NeydnpmCfMnTJs9XZ.png",
    "olympic channel hd": "http://torrent-tv.ru/uploads/3rHDtuBvfq5GWQbPhW7hDEcYeabTwO.png",
    "комедия тв": "http://torrent-tv.ru/uploads/L2MEpT2YePoDvmKRjYy6yyt5ssH1m4.png",
    "союз": "http://torrent-tv.ru/uploads/YpsuBorUwulPHW3nI8O6nKETnEVB83.png",
    "viasat sport sverige": "http://torrent-tv.ru/uploads/prAZKkny3W1HGM03lP0EhzcMmTPZdi.png",
    "ru tv": "http://torrent-tv.ru/uploads/161.png",
    "драйв тв": "http://torrent-tv.ru/uploads/pmmgMKcRbxeYkjVUVr4IAWM0UuZHO4.png",
    "первый канал (европа)": "http://torrent-tv.ru/uploads/WimZD6efLd6QotrPP9uiJeF7t50nFv.png",
    "shant tv": "http://torrent-tv.ru/uploads/IgJpH1JzyjI55Ki2G2Ybz6jzOkwG0T.png",
    "черновицкий проминь hd": "http://torrent-tv.ru/uploads/Us5Sr5jEx6SA6eBdZA9xchHzj1hJ4t.png",
    "bridge hd": "http://torrent-tv.ru/uploads/mdrPlCxp5fwHmCcwMcUzPN3IVRzlca.png",
    "тдк": "http://torrent-tv.ru/uploads/eSrHE6Gws4U6JxhFXA3mQ4iDVc0SwS.png",
    "карусель": "http://torrent-tv.ru/uploads/S233D4b6eq7KOXfdyi4dY2GokKeltg.png",
    "travel channel": "http://torrent-tv.ru/uploads/fhmrYjlpC0YMxFd2RqOolbjlXMr0tI.png",
    "ттс": "http://torrent-tv.ru/uploads/crsSIipA6N288sjn4EvUyOyTd0ed9A.png",
    "0x0 music hd": "http://torrent-tv.ru/uploads/hFj4tnC5uqAgpod3doHnJGZxgZXaiP.png",
    "музыка первого": "http://torrent-tv.ru/uploads/fD2Hnsq5BPMGvobLDMPZP049yNhBYt.png",
    "brodilo tv hd": "http://torrent-tv.ru/uploads/0pLPWiGqZjDe2O4vbPd8QL0qGsA9lq.png",
    "5 канал (украина)": "http://torrent-tv.ru/uploads/9La0uS6S8rMKr0BOh6vSCQLNiCqN7N.png",
    "ночной клуб": "http://torrent-tv.ru/uploads/nXifSdkxHJVKI4SKtgtBQmCSHXtgOt.png",
    "центральный канал": "http://torrent-tv.ru/uploads/vzfLS14qVT0rSphoNeEuO2WDvXFoub.png",
    "interaz": "http://torrent-tv.ru/uploads/rdntbmpYEYtyRbW3nGa1FUNZPXF53O.png",
    "русский бестселлер int.": "http://torrent-tv.ru/uploads/b5JXaosgmcanh9EVJg52yBefvdLQF7.png",
    "xsport": "http://torrent-tv.ru/uploads/SCwOf3movQkrJf7ez4tNLZYlWo1b7t.png",
    "bollywood hd": "http://torrent-tv.ru/uploads/HXzWxtMxmXkrpgr88Kh8Z1A8F6o5dK.png",
    "матч тв": "http://torrent-tv.ru/uploads/hQDOuQjUVczvUU2ocLE0tkC1siCqpo.png",
    "tv sale": "http://torrent-tv.ru/uploads/hs0YdiUTlpRtb3wTiP4cXboX0H9oTN.png",
    "trt turk": "http://torrent-tv.ru/uploads/BDkqm302OLdoXCwpKFVUe8S43OlWj9.png",
    "твц (+4)": "http://torrent-tv.ru/uploads/dR7hMBOIq0MDGMkydFuksHGLNIWz7U.png",
    "cctv news": "http://torrent-tv.ru/uploads/TyWVFvKwV3lOYYXWVJSj8HMu5AodJr.png",
    "москва 24": "http://torrent-tv.ru/uploads/dZcmoqRoZLhCBh8BE4RnbQivuDY6hH.png",
    "world fashion": "http://torrent-tv.ru/uploads/2YI4sT9YkGezrw9vZPn0uIRhZ7E2BV.png",
    "47 канал": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "первый канал (молдова)": "http://torrent-tv.ru/uploads/UsbyyrSaJmdjntY4muATwDytnseYYB.png",
    "n4 tv": "http://torrent-tv.ru/uploads/R1NDSrUKnB1RoT8iv1okSe2xY39W4J.png",
    "telesur": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "первый музыкальный россия hd": "http://torrent-tv.ru/uploads/h7EDhdGypKmtfEP98O052SLlXUCcXt.png",
    "онт (беларусь)": "http://torrent-tv.ru/uploads/a84If8XdqSFa6nHpegdujt52vAGNJW.png",
    "hit tv": "http://torrent-tv.ru/uploads/FnCnW1vmvm8gjAwMGXe2Q8qtN1C3zy.png",
    "курай тв": "http://torrent-tv.ru/uploads/A0onEnFhSzqGxckeyyXsf0ZQ4R3Vc6.png",
    "новый христианский": "http://torrent-tv.ru/uploads/gf6hTOcGXasvr47vTFRYZGV11xkDr5.png",
    "cctv 9 documentary": "http://torrent-tv.ru/uploads/dqoArqO8dd09vzsSSQPqLUj5wM9O9M.png",
    "детский": "http://torrent-tv.ru/uploads/jk8kody2p38CKdj5KGXWMwRLjgFIlG.png",
    "amedia 2": "http://torrent-tv.ru/uploads/fAvxTQbWu0DAcMkqej0m73KohAcQJw.png",
    "amedia 1": "http://torrent-tv.ru/uploads/jT3vAEOG5jTd2t8GcC797Bw5W0kSl9.png",
    "lifenews": "http://torrent-tv.ru/uploads/K8dBCUNz1BSwbgUYYU04i2qJpQKLMc.png",
    "стс (+2)": "http://torrent-tv.ru/uploads/FWNPupxL8N0STWKYEryyiV5sDFN2tS.png",
    "тнт-music": "http://torrent-tv.ru/uploads/buHzdmouswQyLnhzwqnPUHdS9BMHTw.png",
    "music box tv": "http://torrent-tv.ru/uploads/fvt4pris0lwnVhSyUrh8QlyzWBhbgz.png",
    "рен тв": "http://torrent-tv.ru/uploads/LJvkfB2kYaDzij1Y13Fy6syUCkP5Y6.png",
    "glazella hd": "http://torrent-tv.ru/uploads/7EM3eHww2EvOf9jgeFPdZrsQwO8Fz7.png",
    "nhk world tv": "http://torrent-tv.ru/uploads/JJ8Sh9c7zA3PaXlK1ZaNjy3GgWQFh2.png",
    "пушкин - царское село": "http://torrent-tv.ru/uploads/Oq0JHpGCMDNzpjf85X7Az3PPPkmDs5.png",
    "еда тв": "http://torrent-tv.ru/uploads/TWdAdMXfMSylb2mQ4efFnOAYosymNC.png",
    "mtv россия": "http://torrent-tv.ru/uploads/P5ijp2sRQsKVZkOJwjdqIVgYdJzhpZ.png",
    "tv 1000 русское кино": "http://torrent-tv.ru/uploads/ch5DX6f8hxDnmyzrjotUoKHNGzcw9P.png",
    "первый музыкальный россия": "http://torrent-tv.ru/uploads/MkX2WG1zhZ2KcYFdL0xWH1T4xkO7UW.png",
    "пятница": "http://torrent-tv.ru/uploads/0fafj6PSIWdqtBdgwYTl9M06SDU2wA.png",
    "кинопоказ": "http://torrent-tv.ru/uploads/v0JEbxExcFI8dVEzCkpZUoktgiS9t7.png",
    "bbc one": "http://torrent-tv.ru/uploads/ofuDCyM7MgzwFbzG2pyavFu6xeRHwp.png",
    "n24 hd (germany)": "http://torrent-tv.ru/uploads/j0NiKCcpOnPBobWAE0CVBLsBhSLgCt.png",
    "russian music box hd": "http://torrent-tv.ru/uploads/CbPggS9SpKMrgFW5myDvhLEFvm0hwp.png",
    "наш детектив hd": "http://torrent-tv.ru/uploads/ORgdUno4IvNQYiShiEY4srF16JguLs.png",
    "fap tv pissing": "http://torrent-tv.ru/uploads/3QJ9sSAI90ALizvl1B2sbt8WxIVLSu.png",
    "мир (+3)": "http://torrent-tv.ru/uploads/QxOYkz6f80IdhmC4RSHI1cMd32CqYZ.png",
    "playboy tv": "http://torrent-tv.ru/uploads/lIWBxmt5GDl9tg4KsQNtA0CuZWdOHH.png",
    "b4u music uk": "http://torrent-tv.ru/uploads/LlfDsq3FEU2D4P3lmj25fvl6zQnvNM.png",
    "стрк hd сочи": "http://torrent-tv.ru/uploads/2PphESGueDUS1T6wSOr12iTgTbIVJm.png",
    "наше новое кино": "http://torrent-tv.ru/uploads/y5jtghJCHG65ukyfjv%2045stjxc76.png",
    "матч! арена": "http://torrent-tv.ru/uploads/DDjh1dM2D09Wcl3L6YmEd1si3P17n0.png",
    "nickelodeon hd": "http://torrent-tv.ru/uploads/CFYx7Bd1aDSgkqjMLLQjFE6xe3u1E0.png",
    "dot dance hd": "http://torrent-tv.ru/uploads/Z8TDmebVzyNS57me2IO2rd2LaiNRM6.png",
    "news one": "http://torrent-tv.ru/uploads/SnaQqBa1YMS2b8b8EGdZSMCConLbDS.png",
    "phoenix cne": "http://torrent-tv.ru/uploads/4A3PI1xIjIeECNSMDDvOfwXd5n2sso.png",
    "калейдоскоп тв": "http://torrent-tv.ru/uploads/YJMqmzlZ87QeXYm9XpjH0XzpjljNcU.png",
    "tv3 catalunya": "http://torrent-tv.ru/uploads/JdogLgSiKoXxC7ZlxVLogeOLMQUQyN.png",
    "мир 24": "http://torrent-tv.ru/uploads/auv6717gJOWi0A2VoeDQaCsx9G1NOj.png",
    "tv mall": "http://torrent-tv.ru/uploads/hao8n2RWJzxwNaiVHUawwkNVG6X4Zp.png",
    "ю (+2)": "http://torrent-tv.ru/uploads/YvnG7hXCwMmHnakp2KkCbqeCigHcuK.png",
    "dota 2 tv hd": "http://torrent-tv.ru/uploads/Ii6xQm0v1eHLTMgB0CnKooifWltnig.png",
    "tv 1000 action east": "http://torrent-tv.ru/uploads/GblbxkDGXZyW5oWt9W8wuERQAiZ7ZT.png",
    "shop 24": "http://torrent-tv.ru/uploads/bCuxLyvoTk8l5cBRSyKFXjWjYucvlu.png",
    "france 24": "http://torrent-tv.ru/uploads/pViXgcMjLnB5WyOoQJ7sBxhHo5fTSB.png",
    "авто 24 hd": "http://torrent-tv.ru/uploads/GZwKgvkC0vfYquFAn1dKhppNxdDit9.png",
    "eurosport 2 hd": "http://torrent-tv.ru/uploads/0mo5WOW3xn7FmcIRM9PMZxb2Zgad86.png",
    "пик hd": "http://torrent-tv.ru/uploads/P0YqVS65dvcrXyt5BDd0bx02EtK9HC.png",
    "футбол 1 (украина)": "http://torrent-tv.ru/uploads/AMKtYwcgSAX5mTcPdhQDe4he18Jz7S.png",
    "тв 3 (+3)": "http://torrent-tv.ru/uploads/427.png",
    "охотник и рыболов hd": "http://torrent-tv.ru/uploads/O0wexOqiQXKMwr2coDMKWvJEb4zLQ1.png",
    "national geographic hd": "http://torrent-tv.ru/uploads/hK1waimMq9eAp0ugM19moSoQvUeve5.png",
    "дом кино": "http://torrent-tv.ru/uploads/jlC78Fy13KWjQUN6l3FtbsRLZDvc0x.png",
    "vh1": "http://torrent-tv.ru/uploads/58.png",
    "театр": "http://torrent-tv.ru/uploads/8qawrcOtzHZTAa3kI0rcDfVFEZoI5u.png",
    "amedia hit": "http://torrent-tv.ru/uploads/3lKypp7zXsJ3FDusXzKw9hHnVLythX.png",
    "8 канал (красноярск)": "http://torrent-tv.ru/uploads/wKPUJjcpZIfI5zBSZwNayOlv63zRNV.png",
    "az tv": "http://torrent-tv.ru/uploads/FB2qxgNm8xTU6YiR2fY1jH4PIRR2SF.png",
    "idman tv": "http://torrent-tv.ru/uploads/UhhUZdtM7FjDFbmoleWalj7tp6nj5o.png",
    "нтн (украина)": "http://torrent-tv.ru/uploads/LpQE1Odb1EoH5dJ90gWjItVyEYBXsw.png",
    "архыз24": "http://torrent-tv.ru/uploads/tuMbRlnkeMiYQ6u9oeiAVfHF0F20RB.png",
    "первый канал (+6)": "http://torrent-tv.ru/uploads/45vL1pa1DYHjYyMs1dtGC9RsACLmz3.png",
    "винтаж тв": "http://torrent-tv.ru/uploads/6yngbEKfgy6XtMw28INQCoOdulf2tC.png",
    "трофей hd": "http://torrent-tv.ru/uploads/cPi9B0icZpuvSRQiH0Kk6rNY8r1X65.png",
    "fap tv trans": "http://torrent-tv.ru/uploads/05P2Z8lWWIgaEmvWcTRO1R9F0lMPZL.png",
    "sky sport 2 hd de": "http://torrent-tv.ru/uploads/4dPVkJ96LwrNCbFCii8dJwJC1wEAzJ.png",
    "shopping tv": "http://torrent-tv.ru/uploads/Yhipu86vXMGf0hxCTXLezpGpcUbibW.png",
    "viasat sport": "http://torrent-tv.ru/uploads/prAZKkny3W1HGM03lP0EhzcMmTPZdi.png",
    "трофей": "http://torrent-tv.ru/uploads/tQTWwjNBC8aLLWiWZfCj43BhWNH51I.png",
    "dange tv": "http://torrent-tv.ru/uploads/ofmgiZlRmwOZtTaYtUtfErZS3ODDDM.png",
    "bridge tv classic": "http://torrent-tv.ru/uploads/DsJRpcbI6rgjONbQftC5nHt1XMAXYQ.png",
    "тнт4": "http://torrent-tv.ru/uploads/yTclqOAW0EWwhw9vt0spVSUcS70ZR0.png",
    "paramount channel": "http://torrent-tv.ru/uploads/Iyzjhb5BBRKfvEZdBwNJ785jzroODU.png",
    "mcm top": "http://torrent-tv.ru/uploads/b4SLIxXFbKUErZxBXfGoo6eQN5Mu38.png",
    "домашние животные": "http://torrent-tv.ru/uploads/HiWAmn5RvUKNJnSW2Jhxjs6maoNFV7.png",
    "fоx life hd": "http://torrent-tv.ru/uploads/Vou521VpOGAGqhp4HUfiG7BSbKNSk6.png",
    "viasat fotboll hd": "http://torrent-tv.ru/uploads/0JLqj3qwFoT1Y61scCyUdWioV5U6hx.png",
    "hd media 3d": "http://torrent-tv.ru/uploads/takNty6pirY7TeCRPX5VyUW1mZHHxI.png",
    "fap tv bbw": "http://torrent-tv.ru/uploads/PHnwbskpP4oixpMjlJKgGvTAajXFSg.png",
    "оружие": "http://torrent-tv.ru/uploads/CyDUCmYXK8WS2kXCX5kiAOFejnlwoP.png",
    "звезда (+3)": "http://torrent-tv.ru/uploads/IVxzhUbLe9DUhOtnjpDYpITMrBdybS.png",
    "первый деловой": "http://torrent-tv.ru/uploads/a1Qf3MpxC9FPD68Tj8vtUTNK8P25xr.png",
    "тнт (+2)": "http://torrent-tv.ru/uploads/Vtt1KKIpLY4LTQGnV03sdBYyX3hyWR.png",
    "кхл тв": "http://torrent-tv.ru/uploads/216.png",
    "рен тв (+2)": "http://torrent-tv.ru/uploads/WeHcyu6MG9GGpCmToRQnoL97iesKk9.png",
    "fashion one hd": "http://torrent-tv.ru/uploads/iPs2ptiBXm8h0KSnRmyqu45texHNig.png",
    "russia today arabic": "http://torrent-tv.ru/uploads/OPbYfpQc4ShP8JmgPeiavUroY98H8L.png",
    "донбас": "http://torrent-tv.ru/uploads/vsj1IA3Z8QVL3AzzuN4EshgT4LUmRr.png",
    "tvt 1": "http://torrent-tv.ru/uploads/CKKdhDfmno9O52tMfWptiAQT0IBWV8.png",
    "c more tennis": "http://torrent-tv.ru/uploads/ql4qy7gHN4GtWhcqfd97HqXUs8HXI9.png",
    "eska wawa tv hd": "http://torrent-tv.ru/uploads/r9d697qox4MFgypnVqeILYWKcfbwNc.png",
    "ювелирочка": "http://torrent-tv.ru/uploads/pvKHFUCv25R51hJoUpAJfvjGnWyqoZ.png",
    "mgm hd": "http://torrent-tv.ru/uploads/o4K0lgc2D1GkuFwMC3Cdg1uK6fMrG4.png",
    "кинопоказ 1 hd": "http://torrent-tv.ru/uploads/pNA1vR3sPoovYNKzO4TU6NQcSXNqjk.png",
    "fap tv 3": "http://torrent-tv.ru/uploads/S5gXPPcF53lFHQ3kgJofKMQudRQKPt.png",
    "музсоюз": "http://torrent-tv.ru/uploads/E4a3fEpdSy2c8AnYEdR8ZIFgFe2LAP.png",
    "1+1 international": "http://torrent-tv.ru/uploads/o6wtkD3LF7NT4yADrcoBrXVWDDrvgV.png",
    "fap tv 4": "http://torrent-tv.ru/uploads/xv1QyBV2OkaDbZ1ebRB2FWwfw40BR5.png",
    "онт (одесса)": "http://torrent-tv.ru/uploads/P3tnfUDZ7f025rw6X7rFNT4aYmwMlJ.png",
    "первый канал": "http://torrent-tv.ru/uploads/WimZD6efLd6QotrPP9uiJeF7t50nFv.png",
    "усадьба": "http://torrent-tv.ru/uploads/5yIxLQzQyZnH5EJcwpSGb28QuRTSFH.png",
    "оплот тв": "http://torrent-tv.ru/uploads/gvofGxTug45qSt1vsX0BPzQxGTrwTr.png",
    "animаl planеt hd": "http://torrent-tv.ru/uploads/9HZGan5rQItVQOfnB91FGqyJXjoqYV.png",
    "amedia premium": "http://torrent-tv.ru/uploads/ornzQpk6WCW6xk0lyBhlwqH8u2QyU7.png",
    "cbs reality": "http://torrent-tv.ru/uploads/QbWaD2vNgLRLY0Hsccg3nf9azAXRld.png",
    "пиксель тв": "http://torrent-tv.ru/uploads/BdCXB7wPZMNvlWzB5xEFzmsYUXcfXW.png",
    "киносемья": "http://torrent-tv.ru/uploads/y2oerfuhdj2108nbs4ev875esk47dn.png",
    "русский роман hd": "http://torrent-tv.ru/uploads/2smriIFxtj7Ojh4jyZq0K1XrT98XjS.png",
    "lider tv": "http://torrent-tv.ru/uploads/LByLhdeQ30Ln5pSZRYSpoLpXQS5Ytr.png",
    "fap tv shemale": "http://torrent-tv.ru/uploads/d5ulbooZicKw3aMLwn2Ho0yD9c46T2.png",
    "tonis hd": "http://torrent-tv.ru/uploads/38BRA5jO6LAsQ6rv1NC3FMJ6KALp8z.png",
    "карусель international": "http://torrent-tv.ru/uploads/S233D4b6eq7KOXfdyi4dY2GokKeltg.png",
    "lrt": "http://torrent-tv.ru/uploads/sgH7Pdrd27V3cvlvg8OFOzsL2gLbcF.png",
    "history channel hd": "http://torrent-tv.ru/uploads/VFgU260pmiIyPxCzD3f8R7Yc6DXClH.png",
    "btv bg": "http://torrent-tv.ru/uploads/VJnbuhCGi2Ny1uLFAD9beZoRI9UWfY.png",
    "русский роман": "http://torrent-tv.ru/uploads/2smriIFxtj7Ojh4jyZq0K1XrT98XjS.png",
    "тиса-1": "http://torrent-tv.ru/uploads/pPRRy0SjPl3JKXdcZrQrdXQz3NTKOH.png",
    "детский мир": "http://torrent-tv.ru/uploads/00Vf3rPABNnbNQ6Rv0dnfcg3JsJelA.png",
    "tonis": "http://torrent-tv.ru/uploads/38BRA5jO6LAsQ6rv1NC3FMJ6KALp8z.png",
    "discovery channel": "http://torrent-tv.ru/uploads/oKx1ImWVRT3AK3DHYWUVc71JZUkwu5.png",
    "100% news": "http://torrent-tv.ru/uploads/9yEWvPmTcFS8lyQ5NjJ7vbYOa3bx1W.png",
    "мир увлечений": "http://torrent-tv.ru/uploads/KtELENmDesBwzAAryLgJPqwlr9m17z.png",
    "малятко тв": "http://torrent-tv.ru/uploads/kjYF9vS2IDTMehpzC7WWfjnZ4NVpuk.png",
    "тро союза": "http://torrent-tv.ru/uploads/xAXy9iMyJ4wa2wmugJvbZuDIzc9pVz.png",
    "deutsche welle": "http://torrent-tv.ru/uploads/RnqBDfde1HP4OkZhXWlKB1xkHi6Io9.png",
    "extreme sports": "http://torrent-tv.ru/uploads/21FhIqWK82JDPNuLTEIC9hSO2EHfks.png",
    "arena sport 2": "http://torrent-tv.ru/uploads/QWlwDu4FRIilHsC6ZFR6BdFW8qtvnb.png",
    "bridge tv dance": "http://torrent-tv.ru/uploads/ofmgiZlRmwOZtTaYtUtfErZS3ODDDM.png",
    "islam channel": "http://torrent-tv.ru/uploads/XqP875iZVDQXcyNB4AnAEZ4n3PX9xs.png",
    "arena sport 1": "http://torrent-tv.ru/uploads/EK2c3dIiDNuYQ9zdlASOTaJabNf4gI.png",
    "первый республиканский": "http://torrent-tv.ru/uploads/Ubch3Ma8hsdSd8u6spOxVK5bZYsnDs.png",
    "россия 1": "http://torrent-tv.ru/uploads/UUrfoqi6NQcc9gRLnCc8ODZJ2T3ShE.png",
    "ua:перший (украина)": "http://torrent-tv.ru/uploads/iN5vheceBnPmO18uXHGgKwq7q2PHtF.png",
    "футбол 1 hd": "http://torrent-tv.ru/uploads/hZaWPKLVxTqUWZk0LTmLi1K1WUzX85.png",
    "охотник и рыболов": "http://torrent-tv.ru/uploads/Ws2ddPI0b5Ie7PymoPUsboVlz9lYMS.png",
    "загородная жизнь": "http://torrent-tv.ru/uploads/cGGo8HRkVhy66UXKXZ4tH5HyUaaxJA.png",
    "luxury world": "http://torrent-tv.ru/uploads/QvaV83TwgWHnaGmw4C822MCNYi9zio.png",
    "глас": "http://torrent-tv.ru/uploads/6m1xUI7vFyadFMFxXeIZjlATt7rlWw.png",
    "fap tv amateur": "http://torrent-tv.ru/uploads/LGfemDTp3Z3mvhn1aKSGVvtlNu5zMF.png",
    "outdoor channel hd": "http://torrent-tv.ru/uploads/SuxFoocUmay5G8jtfJaHL1yIbAT5Hr.png",
    "нтв+ наше новое кино": "http://torrent-tv.ru/uploads/RcsEz5rIV3hQ6cwn6hqiwNAEOh1zNp.png",
    "brazzers tv": "http://torrent-tv.ru/uploads/VPCmFsMfpnB0pg9VBzvUG5TkRcHTsR.png",
    "нтв (+2)": "http://torrent-tv.ru/uploads/B5GA1cfgmn8EsxrdwfNUIrEbdqarXf.png",
    "матч тв hd": "http://torrent-tv.ru/uploads/MXyy9Uud7oDuH8JqVisjsD0csgAHnQ.png",
    "epoque": "http://torrent-tv.ru/uploads/eULbHv3DyublWF2rAhw38DV63cV3V9.png",
    "fap tv older": "http://torrent-tv.ru/uploads/G1L5Qh2QVnSu6zEVua6KOI4hxtUfcn.png",
    "авто плюс": "http://torrent-tv.ru/uploads/WkRxjy6fJEBJ5NZiaGn2j05eqfFfQq.png",
    "djing ibiza hd": "http://torrent-tv.ru/uploads/aGqPHXL6MxB8j4GXldadnOR3r5D03f.png",
    "первый городской одесса": "http://torrent-tv.ru/uploads/vBOI3YTA4FDLD0c7BHHjq476p9GMCZ.png",
    "travel + adventure": "http://torrent-tv.ru/uploads/b1HifWKMyefmDDvaDAJTwNNTaD8LF4.png",
    "про все": "http://torrent-tv.ru/uploads/S2i01pmEOFJxwJtJCVF7PYc6Ij4jBX.png",
    "trt muzik": "http://torrent-tv.ru/uploads/ynONGPWT3nA6k9ZmprRl1hSW9fLWBX.png",
    "ю": "http://torrent-tv.ru/uploads/YvnG7hXCwMmHnakp2KkCbqeCigHcuK.png",
    "nick jr.": "http://torrent-tv.ru/uploads/D87kJ3fIWIm5wKi5qxm24nbuPQv0U8.png",
    "112 украина": "http://torrent-tv.ru/uploads/0AUjU7DOzZcpizC4UR19vDZqqthSe0.png",
    "мир белогорья": "http://torrent-tv.ru/uploads/JRU6TyiBAX5Fk84DebhKeSxg7ZkrEf.png",
    "пик": "http://torrent-tv.ru/uploads/P0YqVS65dvcrXyt5BDd0bx02EtK9HC.png",
    "al jazeera english": "http://torrent-tv.ru/uploads/B1AC3jl0CY8u4qxO0aIEHVMFQFvBUu.png",
    "anyday hd": "http://torrent-tv.ru/uploads/r8hT8FoPXteOKe9H8FjQTdIttfOg8S.png",
    "viasat sport hd": "http://torrent-tv.ru/uploads/prAZKkny3W1HGM03lP0EhzcMmTPZdi.png",
    "россия hd": "http://torrent-tv.ru/uploads/ghvqmVpPWqn9x6POAm9UJBvXFzTrqN.png",
    "cgtn documentary": "http://torrent-tv.ru/uploads/dqoArqO8dd09vzsSSQPqLUj5wM9O9M.png",
    "russia today doc.": "http://torrent-tv.ru/uploads/VOYx5PIhDPrWiZIcCYpm1xrDSQZnsN.png",
    "btv comedy": "http://torrent-tv.ru/uploads/OTlo37AAbW4Ef4dNxVgYBqcBztrBlI.png",
    "food network": "http://torrent-tv.ru/uploads/W68LEGlOOMPtN0qoGXvdkWhHBjKet6.png",
    "пятница (+4)": "http://torrent-tv.ru/uploads/hCwKaMG6bApehKr68iauaJa68ZC3W1.png",
    "морской": "http://torrent-tv.ru/uploads/uzlb3awoyNqvIcf6i35hTVqf7gvuqz.png",
    "sony turbo": "http://torrent-tv.ru/uploads/CaPjVaQrpyN138TarQ7CYBqBOz0ZF7.png",
    "r1": "http://torrent-tv.ru/uploads/zI5CoA2qyiJYuXzqsXo0LBmJv9Tern.png",
    "тв 3 (+7)": "http://torrent-tv.ru/uploads/HfEo6PctsuTnlPQIa0xVKgEDqFwI48.png",
    "юмор тв": "http://torrent-tv.ru/uploads/6VFA1SVxeFHUsGaKPbNxWZREDkGeZw.png",
    "к1": "http://torrent-tv.ru/uploads/mk2mYb28HFIxkFIiMNQWmKUdn1Y8hD.png",
    "к2": "http://torrent-tv.ru/uploads/IjG76jf8k8HTNLooNpUiEXtkPfA2rG.png",
    "mtv am hd": "http://torrent-tv.ru/uploads/4jFcW4ycRkxdcHqHaVM8J2oIxV7re8.png",
    "vinyl tv": "http://torrent-tv.ru/uploads/qJpayWFPo9N5mYUIHK1phkAi1fd0Y9.png",
    "atr": "http://torrent-tv.ru/uploads/uggqxQxxDTuz1P1mY4PZdlRcAKow3F.png",
    "9 канал израиль": "http://torrent-tv.ru/uploads/dsi2SD7Pmq3sxxaNPpRAUgKmxXh4s6.png",
    "fap tv legal porno": "http://torrent-tv.ru/uploads/QMv8xcYgTaW9108ymib6XyWXRMI7dn.png",
    "cctv русский": "http://torrent-tv.ru/uploads/DcaE92lKRSDFBPlYUnsNRauFLbotKu.png",
    "матч! арена hd": "http://torrent-tv.ru/uploads/DDjh1dM2D09Wcl3L6YmEd1si3P17n0.png",
    "еспресо тв": "http://torrent-tv.ru/uploads/lOwm890F5URuR5Ej7IacerzECPIDt4.png",
    "эко-тв": "http://torrent-tv.ru/uploads/EmsE2NuqzHi5NXh6OIMMXQpfmD0VIl.png",
    "ескулап tv": "http://torrent-tv.ru/uploads/onT5lg0NOm9BSORR7KNsO1oRA9pY1S.png",
    "shop24": "http://torrent-tv.ru/uploads/bCuxLyvoTk8l5cBRSyKFXjWjYucvlu.png",
    "мужское кино": "http://torrent-tv.ru/uploads/PUDb8m2JFLndsPvb56tdH0V4RW0kZc.png",
    "кухня тв": "http://torrent-tv.ru/uploads/G0WbVMphlP9oJ6KvHRfx0xDfhrF9Re.png",
    "paramount comedy hd": "http://torrent-tv.ru/uploads/AvH8i4NV780Q7PcHi5KkxnCDU0Y0yl.png",
    "феникс+ кино": "http://torrent-tv.ru/uploads/idiNkkBsxLwxWCF2VZrc9LQEevKh0d.png",
    "btv": "http://torrent-tv.ru/uploads/52ZaTijyyDOsKI7B1fYnUWliW6i2ah.png",
    "красная линия": "http://torrent-tv.ru/uploads/I43S6jd5noclar0LlPJnyY8adonmUV.png",
    "звезда": "http://torrent-tv.ru/uploads/0HLRrFHt2QIkbJpLc1fy0RVe7hqCEC.png",
    "eurosport 1": "http://torrent-tv.ru/uploads/QA9jgUaQRrE4vMno04eM3aUrklXOce.png",
    "hustler tv": "http://torrent-tv.ru/uploads/wgAR4TI1xdd2LAtnbkpvFAfnnn5Uru.png",
    "globalstar tv": "http://torrent-tv.ru/uploads/Y4kNxgbAnPGCt753P73NzCIbcNz5lD.png",
    "россия ртр": "http://torrent-tv.ru/uploads/5o9OWeEw90hM5ouECuTLwj5QP8MwU3.png",
    "tv5 monde europe": "http://torrent-tv.ru/uploads/ko7rbRBnyK1iINkLOA2adRvgVOEgUK.png",
    "365 дней": "http://torrent-tv.ru/uploads/0IZrVwoxtmjtgnWu5Dj4Hb8FRc8NIX.png",
    "радость моя": "http://torrent-tv.ru/uploads/VRylZFYgFq7AL0FWcbf5JVOX3desn3.png",
    "bt sport europe hd": "http://torrent-tv.ru/uploads/bSSo2ZvtMr0OPp1xM8zCbNml57Kiso.png",
    "загородный": "http://torrent-tv.ru/uploads/RX345W0BBqJbR3XdROHMi4dnbwqwlt.png",
    "самара гис": "http://torrent-tv.ru/uploads/F0vMjPoFdXa0Vh5t17AOwJVJziMBPG.png",
    "чп-инфо": "http://torrent-tv.ru/uploads/Xy7mLl3exaBKuLlDGdrRls6hyR7mSw.png",
    "первый канал hd (резерв)": "http://torrent-tv.ru/uploads/wT8vUxakbehUwgX5lI9qoRAFBa74tx.png",
    "матч! игра": "http://torrent-tv.ru/uploads/urIB7TbFWo36EmXW9eG3w4qre7MdX9.png",
    "спорт 2 (украина)": "http://torrent-tv.ru/uploads/q0PokCXx6jtCHEPMvE42I0pD3ZNY0o.png",
    "ictv": "http://torrent-tv.ru/uploads/YuNtYxhj9vqgTU9kVuz9imhqviY4PZ.png",
    "arte french (france - germany)": "http://torrent-tv.ru/uploads/sbgrI0jzVss2QNJqUCAPWsbL65a2p5.png",
    "стс (резерв)": "http://torrent-tv.ru/uploads/x2SKtaoIFrGOOwIWKMzuPAY9SeTBGv.png",
    "life78": "http://torrent-tv.ru/uploads/ZloJoTx0yurBDfEtB6V91vRuF8mxB4.png",
    "49 канал (новосибирск)": "http://torrent-tv.ru/uploads/WK3XEVPHqpV3VkKEBHi8QSXoPKPj6T.png",
    "nuart tv": "http://torrent-tv.ru/uploads/aqMIuUixqLQYmJITPnOGtFkRPuTqKa.png",
    "тлум hd": "http://torrent-tv.ru/uploads/FhxsethirEr5lhrE54VGA4acHu7MJn.png",
    "travel channel hd": "http://torrent-tv.ru/uploads/zfnAGLCvIu1fx9hfrITAZMoo9HYww4.png",
    "кино тв": "http://torrent-tv.ru/uploads/KkITMDICqC1erWdSqyOqoccqde2wHC.png",
    "охота и рыбалка": "http://torrent-tv.ru/uploads/5l2P20J6ebTh0ptOr27Hh704niP3nU.png",
    "exotica tv": "http://torrent-tv.ru/uploads/K5hm3mURkkDaSc7RI5RDti5edynMGl.png",
    "мега": "http://torrent-tv.ru/uploads/IXY7dRFoq0qCqn4UbY47iP36vVZ6ck.png",
    "ктк": "http://torrent-tv.ru/uploads/BhI4KURCZ3fAgCQcwQWn7vRCJQblH3.png",
    "tsn 1": "http://torrent-tv.ru/uploads/GJsJeixsOKvFaXz8XKqvX4Uh6sUicu.png",
    "fap tv 2 hd": "http://torrent-tv.ru/uploads/KqVXT8GPTPuPEM87hZSqDwajqcBBgY.png",
    "мир": "http://torrent-tv.ru/uploads/Oq6h2IicTagHENQu1mFkjLk5rChMnr.png",
    "stv": "http://torrent-tv.ru/uploads/DbKEKL5gUOFHiruYRjY2H9gTLOV5mu.png",
    "dtx": "http://torrent-tv.ru/uploads/bx7MosYUikfuwwIOzx2elT6Dh7h50I.png",
    "еда hd": "http://torrent-tv.ru/uploads/ojUD1jhpv7HBOLmubpEBOsANkpYNtk.png",
    "наше тв": "http://torrent-tv.ru/uploads/O7Wx8kIB2aXEEmHLwBFIUhxn8B5WQF.png",
    "втв": "http://torrent-tv.ru/uploads/svsUD6TinXyv3B1q5sZf3fI9ebmpaF.png",
    "первый образовательный": "http://torrent-tv.ru/uploads/1kXxtStMuodaPU09H3rla3ry3QA2Wr.png",
    "tv xxi (tv21)": "http://torrent-tv.ru/uploads/TKchoTWZFRMmGDBok08zoEFJ8mJJCe.png",
    "fine living": "http://torrent-tv.ru/uploads/22I1fK1aMCUgeYUCV0K3vwmlJKELZD.png",
    "lnk": "http://torrent-tv.ru/uploads/svzmHjJUDAOijKSBd3HL9XTvBOBPij.png",
    "russia today": "http://torrent-tv.ru/uploads/rL14fwCe8q10mKTchOwLkfwQVki9XK.png",
    "eska tv": "http://torrent-tv.ru/uploads/1KX19DgurgoaSKNTTpjXCeSQr1epwv.png",
    "телекафе": "http://torrent-tv.ru/uploads/fYRFV5oY197jXcyModfWVs0AlrCOIs.png",
    "раз тв": "http://torrent-tv.ru/uploads/CWaPSXdAL4Ejo1wNOqSWNPNVwbbhC7.png",
    "ani": "http://torrent-tv.ru/uploads/vui1cRrE05CZv1N9Qb20jJ6mTFOJue.png",
    "boutique tv": "http://torrent-tv.ru/uploads/bDSWVUfAEYN9VS25roxW52xO1pj6qp.png",
    "индиго": "http://torrent-tv.ru/uploads/dFIp5shmC5DbfWIDVaFh7coAofmLON.png",
    "тнт4 (+2)": "http://torrent-tv.ru/uploads/yTclqOAW0EWwhw9vt0spVSUcS70ZR0.png",
    "music box uk": "http://torrent-tv.ru/uploads/KUbeGDe2HthXSDa8OqMhia0nhTSL61.png",
    "lviv tv": "http://torrent-tv.ru/uploads/VMl4S9yd5IYFAVFaR8XG6KEm5pgVu4.png",
    "real madrid tv": "http://torrent-tv.ru/uploads/KfoLG7goywcRhMMCc3sO8IVwhuATLp.png",
    "нтв+ киноклуб": "http://torrent-tv.ru/uploads/nRnksgRuhojvbFDqh5KZ30XJQ4iyFO.png",
    "music box ua": "http://torrent-tv.ru/uploads/8T7Rnct8q2VHhRm0BcGFxCjxuYEArc.png",
    "fap tv compilation": "http://torrent-tv.ru/uploads/FXT4PI3HHWIGlk49jRpHyGQBTTVbmt.png",
    "russia today espanol": "http://torrent-tv.ru/uploads/zkPwjfFbktNO8EYDaHlYhwAeT88dmY.png",
    "djing classic hd": "http://torrent-tv.ru/uploads/fDCLK7k2nYRKPAD125JdHM5uuEM7bZ.png",
    "iland": "http://torrent-tv.ru/uploads/S2eR34Z8l9ne1lteBOLvknOq64jMJN.png",
    "хабар 24": "http://torrent-tv.ru/uploads/5ucUtr617J0k3od3cVRn1mMy0Ezi1x.png",
    "та-одесса": "http://torrent-tv.ru/uploads/xnCANqGy0KUMtzCttmO9jyZUsXlEEI.png",
    "мужской": "http://torrent-tv.ru/uploads/6YbhuWNqPKQWWsUGbBnSbAbm7IGssX.png",
    "матч! футбол 1 hd": "http://torrent-tv.ru/uploads/9PM8M6cN21wQ3M5isVZgjNepzUI4Ry.png",
    "трк 555": "http://torrent-tv.ru/uploads/z3GvW4WdjwSmsQrfhAIZewEsdH0rsi.png",
    "тв 3": "http://torrent-tv.ru/uploads/427.png",
    "mute tv hd": "http://torrent-tv.ru/uploads/hlnSJQ7CeTNjKR9FmOki97DzTTgyLJ.png",
    "успех": "http://torrent-tv.ru/uploads/RLcfsouYRxTNrQT97AOPIYfSneJyB6.png",
    "bnt1 bg": "http://torrent-tv.ru/uploads/zLf4TgC4afxKrioUzjsSKdwxOAot3q.png",
    "a-one ua": "http://torrent-tv.ru/uploads/8rEKNCXhKeWnUvGhWCsrb2RN5FMqJi.png",
    "cbs drama": "http://torrent-tv.ru/uploads/1Mcq9jbl7qPeXpT0bbPTnf8aM3f7dq.png",
    "viasat history": "http://torrent-tv.ru/uploads/MWGbB8wJp5Gm4vbPHl0ktohDDjMKdr.png",
    "тагил тв": "http://torrent-tv.ru/uploads/ubegTi3hkdx7xtZCdOz8K0gBQLlght.png",
    "super tennis hd": "http://torrent-tv.ru/uploads/mjQW91VJdjIEhADvOO2s6OiKNeUdUK.png",
    "chasse et peche": "http://torrent-tv.ru/uploads/0X53uW9WfdUDtISMaT71SaPSf0rv3C.png",
    "luxe tv hd": "http://torrent-tv.ru/uploads/gggiBSZ0905Dkcxtdj8Mh8ie14kpPa.png",
    "бст": "http://torrent-tv.ru/uploads/05dZ8fzOmf1lXYue2OvVsQ21eIeX69.png",
    "russia today doc": "http://torrent-tv.ru/uploads/VOYx5PIhDPrWiZIcCYpm1xrDSQZnsN.png",
    "отв (приморск)": "http://torrent-tv.ru/uploads/W3FNGLfo7R7JpYI98Am5sGamz0bfaN.png",
    "2x2 (+2)": "http://torrent-tv.ru/uploads/ZPOhZle6vrDaulo2KMmyrCkkkLn7Ci.png",
    "первый канал (4:3)": "http://torrent-tv.ru/uploads/WimZD6efLd6QotrPP9uiJeF7t50nFv.png",
    "киносвидание": "http://torrent-tv.ru/uploads/y1876iuyf7645urjg56utfy.png",
    "просвещение": "http://torrent-tv.ru/uploads/Fpx3Vqqk2VNcXl4YjsfO53XscWadvF.png",
    "спорт 1 (украина)": "http://torrent-tv.ru/uploads/XqwvMS8Hn0mOpbh79esrIqELTsvo5b.png",
    "rai news 24": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "set hd": "http://torrent-tv.ru/uploads/sX1unYoKj8JR7m8lbtkmPCClRrjAZ9.png",
    "стс": "http://torrent-tv.ru/uploads/is620Pu6DreVLLnpHkpcXXZC9PI2Hi.png",
    "24 украина": "http://torrent-tv.ru/uploads/XfKEdfsy4S1zbE8n2tB1tNNe9IkrRP.png",
    "первый автомобильный (украина)": "http://torrent-tv.ru/uploads/oZTXrmNOxeJIVSbnuxqbiuAL3voXYa.png",
    "glazella 3d": "http://torrent-tv.ru/uploads/7EM3eHww2EvOf9jgeFPdZrsQwO8Fz7.png",
    "rtl": "http://torrent-tv.ru/uploads/Ekttfk03O2aNYv6OoYlVFEAykjDzom.png",
    "sky sports f1": "http://torrent-tv.ru/uploads/J9T7KUE84YobHuNThXN6Hl9UG21tD9.png",
    "горизонт": "http://torrent-tv.ru/uploads/f6wqkzO4WZW7D5Z9xIB4VkMRGmgXUU.png",
    "ewtn uk and ireland": "http://torrent-tv.ru/uploads/maP6bdwOGv77xHPvRnKBHww9cmG2oV.png",
    "интер": "http://torrent-tv.ru/uploads/3SP67FapzyZqMVZTPiJIcN09KRkTeu.png",
    "outdoor channel": "http://torrent-tv.ru/uploads/SuxFoocUmay5G8jtfJaHL1yIbAT5Hr.png",
    "еврокино": "http://torrent-tv.ru/uploads/34mszCG0j0Vf6kFcMrLPnFEA8UPdu6.png",
    "canal 3": "http://torrent-tv.ru/uploads/rb39jMz38xLuXKGCuWD2GcHHMEzfX1.png",
    "культура (украина)": "http://torrent-tv.ru/uploads/pyKdve4YhoChQFGSha8J0FBWBf302a.png",
    "мультимания": "http://torrent-tv.ru/uploads/132.png",
    "viasat explore": "http://torrent-tv.ru/uploads/uCqpsdKP0ialUUYxUk2fXshYdYfxzW.png",
    "eurosport 2": "http://torrent-tv.ru/uploads/qYbdkVFDkhGqTAjXlRtIj2Fg45bmrm.png",
    "itv uk": "http://torrent-tv.ru/uploads/7KVbhhLkEPbBLnqTLjknpR4dc5GyYP.png",
    "kral tv": "http://torrent-tv.ru/uploads/pojhh0tCHuXtk5KkqUl5Nd3JUD3gBB.png",
    "пятница (+7)": "http://torrent-tv.ru/uploads/wv5iC4yjqK6BO9gfPl1jMfZ3Dkzu6Z.png",
    "тв 3 (+2)": "http://torrent-tv.ru/uploads/427.png",
    "дом кино international": "http://torrent-tv.ru/uploads/69MqZE2YHJNewQkqRbJea33WuRkKgo.png",
    "hardlife tv": "http://torrent-tv.ru/uploads/fHPc5oaRdIzKpHTqBFnHA4O2LVf91D.png",
    "стс love": "http://torrent-tv.ru/uploads/iciJHbEmJ1hHXAMhzC9cRWhmh9gH0L.png",
    "cartoon network": "http://torrent-tv.ru/uploads/NTNQLLri3Hh9iqYjW7VEkFYJsTLjk9.png",
    "usarmenia tv": "http://torrent-tv.ru/uploads/llpqN7S6EpCPdoYIHjle6gc4cXlk17.png",
    "спас тв": "http://torrent-tv.ru/uploads/pAFeyS1iCV4BybnpnnwjoKm0y0zvaA.png",
    "риа новости": "http://torrent-tv.ru/uploads/DixgG6tVZzcVHO2LPQEx3QrtfoVah3.png",
    "пятый канал (+2)": "http://torrent-tv.ru/uploads/rsEtkBk2ta1Wj1Y8uvxvSm4Vmbycir.png",
    "maxxi-tv": "http://torrent-tv.ru/uploads/uqyYr07PPk2OuEdnNrbkMHVlGZCJp5.png",
    "rusong tv": "http://torrent-tv.ru/uploads/186WxZMn3PGQyMlWsItM9JkSS4Tt29.png",
    "tv1000 megahit hd": "http://torrent-tv.ru/uploads/lVPY7WCjn1WM6NL6tfLFy8iGA4yk3Z.png",
    "brazzers tv europe": "http://torrent-tv.ru/uploads/OmVBp3Kz4Lx722dq2e1OxE26QSxrDA.png",
    "ностальгия": "http://torrent-tv.ru/uploads/tIfiXoDaXoZevuGu9pZJSvX8unv1xl.png",
    "my zen tv hd": "http://torrent-tv.ru/uploads/GkgzM41JkGOhbS33KepRPoAckZv2Xz.png",
    "черноморская телекомпания": "http://torrent-tv.ru/uploads/LJVoPVcJAE0s4DNmXCga0UPZkRkLTq.png",
    "киносерия": "http://torrent-tv.ru/uploads/4TMYdVpZYXafyIumuB5d7PrjFnslyT.png",
    "uatv": "http://torrent-tv.ru/uploads/83AcB7NfDhEh4tEcJx7d5Lm1l6dzpB.png",
    "music box ru": "http://torrent-tv.ru/uploads/zaHCW7nPCyGRnqHDkenCIXo7d6vR7v.png",
    "europa plus tv": "http://torrent-tv.ru/uploads/PkatgpdmA4ArsgSG5shu0ZCQQ5RgMx.png",
    "digi sport 2": "http://torrent-tv.ru/uploads/x1HMd7tDoprxuZvq90Uj2Gb1eEOhTm.png",
    "digi sport 1": "http://torrent-tv.ru/uploads/gk0ajzoQjMHlBKM298kWjcfNy1P8ec.png",
    "360 градусов": "http://torrent-tv.ru/uploads/K4tiqb5ajIgmxqh8X5moJuDjN7q5hx.png",
    "lale": "http://torrent-tv.ru/uploads/99AZ5VwFy9yZrgsdZ6kIxcoYqwSyUH.png",
    "тнт (+4)": "http://torrent-tv.ru/uploads/Vtt1KKIpLY4LTQGnV03sdBYyX3hyWR.png",
    "дом кино премиум": "http://torrent-tv.ru/uploads/uPO7sY6QsL94BV6QZGtLaxmPd75DJB.png",
    "nickelodeon": "http://torrent-tv.ru/uploads/j66xpaZbfiYIgQxv76QAPckPVjmLNs.png",
    "кинокомедия": "http://torrent-tv.ru/uploads/y087hci8ityixcnyxinxoafhiu.png",
    "стс international": "http://torrent-tv.ru/uploads/is620Pu6DreVLLnpHkpcXXZC9PI2Hi.png",
    "вопросы и ответы": "http://torrent-tv.ru/uploads/xbV8M35FkvpieQ3TUEL8fhwU8MzjmQ.png",
    "game show": "http://torrent-tv.ru/uploads/Uc9sBHj0DAYzfXMZmdxeriCBZvUpeb.png",
    "русский экстрим": "http://torrent-tv.ru/uploads/upndVpIdjY3vb5vrituof5UcKISNcQ.png",
    "авто 24": "http://torrent-tv.ru/uploads/GZwKgvkC0vfYquFAn1dKhppNxdDit9.png",
    "inva media tv": "http://torrent-tv.ru/uploads/mGWpCUkls40liFDUVrxhaIAFwYXZSt.png",
    "qtv": "http://torrent-tv.ru/uploads/zmh1xStjBZGJ6U5g3xLoemD2oT3w3h.png",
    "english club tv": "http://torrent-tv.ru/uploads/Hf5RUQ91cEGtHoaK3GK6VIZlJ8Leql.png",
    "set": "http://torrent-tv.ru/uploads/tKzOKIcOQYrFl1VL8B0QqERFXCAYfU.png",
    "nsport+ (poland)": "http://torrent-tv.ru/uploads/SVdxnEDeE280C8YVqsEIsJermTq1Ks.png",
    "nrj hits hd": "http://torrent-tv.ru/uploads/lSwvcnY5XfGEwyrKSvygH73fcYDZKI.png",
    "киевская русь": "http://torrent-tv.ru/uploads/C1AZimW2NnNA17H1uJLxxePUMTPQZ7.png",
    "первый музыкальный uhd": "http://torrent-tv.ru/uploads/YxKl6Jqi6fmlUJjYGPnBhWhntKzI65.png",
    "дон 24": "http://torrent-tv.ru/uploads/qB34tCfiy8RoCwBprbt3yBlb9QTb7i.png",
    "ретро-тв": "http://torrent-tv.ru/uploads/Of6VAxft82OXf1hk4UonRCHTw3MzqD.png",
    "fap tv parody": "http://torrent-tv.ru/uploads/mu4NIjgq7Xu5nt32zTSxGvBOfk90xt.png",
    "громадське тб hd": "http://torrent-tv.ru/uploads/Ovkd9TiVv3nLcKPwQS2wkJ85KyYCMQ.png",
    "ocean-tv": "http://torrent-tv.ru/uploads/cvBAngU16nJU1bEzxAEcMPiPvf7fVT.png",
    "fap tv teaching": "http://torrent-tv.ru/uploads/3MzvfwDLSX8zUmmuO7TpS8O2iD03Tj.png",
    "fap tv 2": "http://torrent-tv.ru/uploads/YVmUBY8cBPO8IoL4djlyeKCDbs6f0p.png",
    "матч! футбол 2 hd": "http://torrent-tv.ru/uploads/8MA3WloO6RsWX8N7Ck5ugek2Kirf4B.png",
    "armenia tv satellite": "http://torrent-tv.ru/uploads/M4UAMT6cEyL3zuim9fzy38vZRkIfKq.png",
    "совершенно секретно": "http://torrent-tv.ru/uploads/BZJQEpa6Y4KL9tQjPHAIxbodw0KAyN.png",
    "тнт international (европа)": "http://torrent-tv.ru/uploads/d4loXdWqOPiwF7thzyBXX8JSspfVjU.png",
    "shopping live": "http://torrent-tv.ru/uploads/HVwxC489SYFr8Ttqs1he9RZjEmJjPn.png",
    "ginger hd": "http://torrent-tv.ru/uploads/eW7CqWW2bppbpKzhNctyElyv5Nzs30.png",
    "кинопоказ 2 hd": "http://torrent-tv.ru/uploads/Yf2XKrtorOF2wSZ23Q9NHhL2MfOcqi.png",
    "ct sport": "http://torrent-tv.ru/uploads/PV2S8pyGWdX9bdVqKtTYJpBycDvlZO.png",
    "любимое тв": "http://torrent-tv.ru/uploads/qVREQyj0rN87jDZ1ylYW0sDvzfNp8p.png",
    "kino space tv": "http://torrent-tv.ru/uploads/28A3JkU9kVHQWimTbBinKpqYyjZHcA.png",
    "ля-минор": "http://torrent-tv.ru/uploads/8FJA3xMMHcrZuGifHViyVQLjVIem5u.png",
    "animal family hd": "http://torrent-tv.ru/uploads/58VN85gBIna4Ko2K2uNeG6ZrfFNTLK.png",
    "первый метео": "http://torrent-tv.ru/uploads/vdA7FKd1SCYhX4ovvzjQEHFdW3uA5X.png",
    "возрождение тв": "http://torrent-tv.ru/uploads/CKWaxJsLQYiJmnkLhtysIn8hb0NK8b.png",
    "eurospоrt 2": "http://torrent-tv.ru/uploads/qYbdkVFDkhGqTAjXlRtIj2Fg45bmrm.png",
    "улыбка ребенка": "http://torrent-tv.ru/uploads/P8aPFN50uJWJHkrqFGb7wgzfaTHUOO.png",
    "россия 1 (+2)": "http://torrent-tv.ru/uploads/UUrfoqi6NQcc9gRLnCc8ODZJ2T3ShE.png",
    "россия 24": "http://torrent-tv.ru/uploads/LWfGV6eICPYL7psaBfw2dOgGrOtHFS.png",
    "че (+2)": "http://torrent-tv.ru/uploads/N7R86wgoPSELhZ9jCeqaykayjU8mbB.png",
    "viasat golf": "http://torrent-tv.ru/uploads/IGpQl5iTxaDEPyKffdDEpU0EU0SPiO.png",
    "rmc tv": "http://torrent-tv.ru/uploads/3CiAgachWg7ohgoU1Gilcm73hXhT41.png",
    "индийское кино": "http://torrent-tv.ru/uploads/y8wvb5nc77vn5c4x8kinv85c7mv6n875c84.png",
    "че": "http://torrent-tv.ru/uploads/Hv36ZG48lg1mm2wdxAo3ju1EFS41Ga.png",
    "virgin radio tv": "http://torrent-tv.ru/uploads/6DgkEMl3HtkpKQbzVovPdSYhy9f3ne.png",
    "тнт (+7)": "http://torrent-tv.ru/uploads/Vtt1KKIpLY4LTQGnV03sdBYyX3hyWR.png",
    "topsong tv": "http://torrent-tv.ru/uploads/DsJRpcbI6rgjONbQftC5nHt1XMAXYQ.png",
    "матч! игра hd": "http://torrent-tv.ru/uploads/urIB7TbFWo36EmXW9eG3w4qre7MdX9.png",
    "centoxcento tv": "http://torrent-tv.ru/uploads/dPuPlqJtkLMRy7NmOhyHDfL0PJqYj4.png",
    "тнт": "http://torrent-tv.ru/uploads/Vtt1KKIpLY4LTQGnV03sdBYyX3hyWR.png",
    "fap tv anal": "http://torrent-tv.ru/uploads/1PVgf85c4DjIsiWEikpEHDV1j1m6ph.png",
    "кинопремиум hd": "http://torrent-tv.ru/uploads/p580CRZ8bBS6dw3plMWhhxXSzQ59uS.png",
    "санкт-петербург": "http://torrent-tv.ru/uploads/sb81YtPOvlHidztMnC5tZPSKkb1uMI.png",
    "mezzo live hd": "http://torrent-tv.ru/uploads/lGOtRiUoGyJUMCtAtUwevBerpQORD4.png",
    "tlc": "http://torrent-tv.ru/uploads/gT4olUY9nFJbGRCdwd7hHJp1NJ5eJr.png",
    "national geographic": "http://torrent-tv.ru/uploads/i6STSw6Hg1wWP18yBAOyKoKpSMeKLu.png",
    "travel + adventure hd": "http://torrent-tv.ru/uploads/b1HifWKMyefmDDvaDAJTwNNTaD8LF4.png",
    "тнв-планета": "http://torrent-tv.ru/uploads/vBMv8AtIpDhBGQLjPoxkko3baWMFac.png",
    "hd media": "http://torrent-tv.ru/uploads/woAI3zcytfbyiX0LBRToKzErJNy1qF.png",
    "fap tv teens": "http://torrent-tv.ru/uploads/7Z9gyzosm1oUC82aFfA3mBG9YAjOrS.png",
    "hit music channel": "http://torrent-tv.ru/uploads/n7tghbIGAAh8cyWe7Li0E2iNEJSqkl.png",
    "царьград тв": "http://torrent-tv.ru/uploads/9DJiua5LxhwBe2Is3l4LDJIH8zf5EE.png",
    "vision norden": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "ua:крим": "http://torrent-tv.ru/uploads/iN5vheceBnPmO18uXHGgKwq7q2PHtF.png",
    "112 украина hd": "http://torrent-tv.ru/uploads/0AUjU7DOzZcpizC4UR19vDZqqthSe0.png",
    "стб": "http://torrent-tv.ru/uploads/saZlIDrdaXWoiQa8sfZp2bEAeH0kXk.png",
    "парк развлечений": "http://torrent-tv.ru/uploads/beyfqyeacrFG0PrOeKUQhzQ4bV6Q5d.png",
    "trt 1 hd": "http://torrent-tv.ru/uploads/JeOdeaDhjMv4C2w3ly974AwMuKyamd.png",
    "lifenews hd": "http://torrent-tv.ru/uploads/Mvurp6cp7Sq2fV3tnFBwPtJy7Ifm1i.png",
    "btv action": "http://torrent-tv.ru/uploads/kyWKTqWS0PBqSn9YLf1uYwbrdLdz36.png",
    "рада (украина)": "http://torrent-tv.ru/uploads/hBFJBYNiqZUom0ooVtNEJKliZwfioO.png",
    "нано тв": "http://torrent-tv.ru/uploads/QuURIfJUmXegxsHMYqMivVwxizbfKd.png",
    "ртр планета": "http://torrent-tv.ru/uploads/wJMTJDEEwIhJWhNL0c6kfs5HVVJOVx.png",
    "mezzo": "http://torrent-tv.ru/uploads/GUzJ4cyK50ZahOSIx6tTbwGLJiUnSA.png",
    "bbc two hd": "http://torrent-tv.ru/uploads/bbUzq7qIDlw2K8zk0oRHZzc4yHJkW6.png",
    "трк киев": "http://torrent-tv.ru/uploads/qW0p5z3De7COmSxTmvJ4ZA2wOuSJjg.png",
    "eska party tv hd": "http://torrent-tv.ru/uploads/MaX9is65hlDpRDwgOikGE2RqMRxn8G.png",
    "enter film": "http://torrent-tv.ru/uploads/8FPA5SCEIj35fBO8yrULnefW4NzIzk.png",
    "первый канал (+4)": "http://torrent-tv.ru/uploads/nHJycH0CkOhPeZ9DmB47iSMWP5HyWz.png",
    "мир сериала": "http://torrent-tv.ru/uploads/n3zRAlCCBLl5WOeunWGpuMmfdvSJcW.png",
    "life78 hd": "http://torrent-tv.ru/uploads/ZloJoTx0yurBDfEtB6V91vRuF8mxB4.png",
    "кино тв hd": "http://torrent-tv.ru/uploads/glnk0UNz0DwfqxgJh4A5Emo0tKrQAZ.png",
    "viasat hockey": "http://torrent-tv.ru/uploads/CuAbCRGdf3Z1FGFiwErTbHZ3lAMJzr.png",
    "трк украина": "http://torrent-tv.ru/uploads/0co3dwhFDhoCVeTbfMV8ASYFYxSrWM.png",
    "конный мир": "http://torrent-tv.ru/uploads/d8gVne1Em14rIfM6pSsiuufXZeYQqi.png",
    "sky sports 1 hd": "http://torrent-tv.ru/uploads/U4ngWpMf0MTbeOpX4Tgxelz0tPCBs8.png",
    "тверской проспект": "http://torrent-tv.ru/uploads/k6RPWpDIwfsOZ5qkqHF5ZdOf5GqfmH.png",
    "россия к": "http://torrent-tv.ru/uploads/W9pWrec1BOJTmj8okrFeyM44wcpyd4.png",
    "карусель (+7)": "http://torrent-tv.ru/uploads/dxRlCEhphFKEWH1MFjRvPOjQpt2KdT.png",
    "дождь": "http://torrent-tv.ru/uploads/381.png",
    "психология 21": "http://torrent-tv.ru/uploads/AyLAdiqcKu5X8ykdLf2bO9HsxMlJdO.png",
    "mute tv 3d": "http://torrent-tv.ru/uploads/hlnSJQ7CeTNjKR9FmOki97DzTTgyLJ.png",
    "ретро тв": "http://torrent-tv.ru/uploads/axrNIB7372SHIRwqT0jBbfyvjSoZ7I.png",
    "чгтрк грозный": "http://torrent-tv.ru/uploads/LqDNdQj6nf4MraZztT6ZnACn7yOJpV.png",
    "tv8 lt": "http://torrent-tv.ru/uploads/X4DIGhjllSDaaXoZ98BrpkFQ2hHfB6.png",
    "nat geo wild hd": "http://torrent-tv.ru/uploads/YYa1wyNA9prFK1APZ2ZSHGirPpm8kY.png",
    "disney channel": "http://torrent-tv.ru/uploads/JxEjTeXwExjnxutQGKJBmMI85tpNqK.png",
    "плюсплюс": "http://torrent-tv.ru/uploads/6gVIy7RMokFO61iVawgwbthe5mhgqm.png",
    "русская ночь": "http://torrent-tv.ru/uploads/9Sh9bJuj6js5AJsypAd6UvwnsIB25R.png",
    "моя планета": "http://torrent-tv.ru/uploads/Qa41eifERrD77xQsmpRGbeTq95Ldlv.png",
    "eurospоrt 2 hd": "http://torrent-tv.ru/uploads/0tv5hm546AKIySs7cpj30LlCOcY0Mj.png",
    "живая планета": "http://torrent-tv.ru/uploads/xgKSMwqBdEyXnbVgb8LtNXSMiaPcOx.png",
    "нтв мир балтия": "http://torrent-tv.ru/uploads/ykpU49Gl1akVkgiVSsCm5B4TjXvQ64.png",
    "hello tv hd": "http://torrent-tv.ru/uploads/o4WXPUTr5f2tuXFdjuLqgEg3qieGre.png",
    "сказка hd": "http://torrent-tv.ru/uploads/dxhsesilX4JjwoCc8Qab4SYe8fxm75.png",
    "12 канал (омск)": "http://torrent-tv.ru/uploads/6DFMdGjXUjvzyk3B5ltbEd8mWVxAcD.png",
    "on tv": "http://torrent-tv.ru/uploads/W4wsmGmpUkVVAhcBocGkPsRA0o1xTb.png",
    "ltv world": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "vh1 classic": "http://torrent-tv.ru/uploads/FhxUFQ2Bsfom4vb8Ce41gFObAbh1Vh.png",
    "c music tv hd": "http://torrent-tv.ru/uploads/YhtkJhsV8NKwm4FGWhQZDmYcW0TYQS.png",
    "футбол 2 hd": "http://torrent-tv.ru/uploads/TTvGrBoRM07MHY4q6bSwfzVuDKEGTi.png",
    "deluxe music": "http://torrent-tv.ru/uploads/3VnQoAyJh3RZM88USPszL1TZIE5t0u.png",
    "время": "http://torrent-tv.ru/uploads/F44yKDJQLsX0llpZ2wupg8V5vHx5fF.png",
    "tv1 lt": "http://torrent-tv.ru/uploads/CXD4Zq54oHMsByuJbWtdIqzD24dVVo.png",
    "киномикс": "http://torrent-tv.ru/uploads/y6b876ih8g7R876hfug3897wrhj.png",
    "sony sci-fi": "http://torrent-tv.ru/uploads/zLWEgf9BbxBr1TR2Qj2NxVQBuPecEP.png",
    "наш кинороман hd": "http://torrent-tv.ru/uploads/NyV9o2C4xIMFxxYUQsS1qsdAtkqz0k.png",
    "сарафан тв": "http://torrent-tv.ru/uploads/LsYzwEOUspoxkY2hrTSy9zKqvpWlY8.png",
    "первый ярославский": "http://torrent-tv.ru/uploads/6FZ4QqwM18DLS3WE6XKeF0rJzpSAIH.png",
    "культура украина": "http://torrent-tv.ru/uploads/pyKdve4YhoChQFGSha8J0FBWBf302a.png",
    "tlc hd": "http://torrent-tv.ru/uploads/gT4olUY9nFJbGRCdwd7hHJp1NJ5eJr.png",
    "кинохит": "http://torrent-tv.ru/uploads/y3igbjZ&LGyqDWGIASUY78AWID.png",
    "зоо тв": "http://torrent-tv.ru/uploads/RtAhntWPlKQs6CIYAb72piNF9EsN3E.png",
    "0x0 fireplace hd": "http://torrent-tv.ru/uploads/RmAQPMASKvUMz6EmmJEMUToLh6mWVT.png",
    "кинопремьера hd": "http://torrent-tv.ru/uploads/y4Ihg8o7ikgJHF768iJHFH76iu.png",
    "крым 24": "http://torrent-tv.ru/uploads/x4s9QQXR8KerO13nlkuEujzcv5ww5F.png",
    "матч! футбол 1": "http://torrent-tv.ru/uploads/9PM8M6cN21wQ3M5isVZgjNepzUI4Ry.png",
    "матч! футбол 2": "http://torrent-tv.ru/uploads/8MA3WloO6RsWX8N7Ck5ugek2Kirf4B.png",
    "матч! футбол 3": "http://torrent-tv.ru/uploads/OLHdmyfUev4mMX0OGniJrlUwHnMKOg.png",
    "круг": "http://torrent-tv.ru/uploads/fbzJYZiRscBiEvaWEFmzvYzEHdaNN7.png",
    "россия 1 (+6)": "http://torrent-tv.ru/uploads/UUrfoqi6NQcc9gRLnCc8ODZJ2T3ShE.png",
    "fox life": "http://torrent-tv.ru/uploads/rkksGUl3DstQSEyT26Q07hNCEwyNnd.png",
    "polonia 1": "http://torrent-tv.ru/uploads/3fzUyCBgUoJ6zqc92KSXh9g9utJEuO.png",
    "муз тв": "http://torrent-tv.ru/uploads/gttVvZmkAklbl2i0Mqy1MCzSCn7WiY.png",
    "9 волна": "http://torrent-tv.ru/uploads/8zDeTSBhsmJDbXo9dxHA1c9mDOP9sP.png",
    "o-la-la": "http://torrent-tv.ru/uploads/7ddvb8Tivq7yuEgffrKildHi2BQcCE.png",
    "тнт4 (+3)": "http://torrent-tv.ru/uploads/dg9BEAtJr4IthpXjxV8NGAiu95NjXl.png",
    "russia today doc hd": "http://torrent-tv.ru/uploads/b8QePfFi6zsCDS7hfTeFWES5UN4SAk.png",
    "bloomberg": "http://torrent-tv.ru/uploads/OTsoNZRT8xjXz5nnTICPCQRvNLjBal.png",
    "tvp sport": "http://torrent-tv.ru/uploads/AkCqdaRAZAZY0PKGoKZkhDlBCF9RR6.png",
    "искушение": "http://torrent-tv.ru/uploads/OQF9mLHIZ87QCphtuNTx6mLJNn5Czf.png",
    "футбол 2 (украина)": "http://torrent-tv.ru/uploads/PUXTI9mKcs49JnEENkh95KoKqt9VNg.png",
    "первый музыкальный hd": "http://torrent-tv.ru/uploads/YxKl6Jqi6fmlUJjYGPnBhWhntKzI65.png",
    "нтв+ наше кино": "http://torrent-tv.ru/uploads/UXJcZjVdZVIzciVHgGT3e6XxdRaBsD.png",
    "ictimai tv": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "tvc 21": "http://torrent-tv.ru/uploads/t6oWXfHEIMAjJ9GSEChuI2JHQg7KzL.png",
    "крик-тв": "http://torrent-tv.ru/uploads/z4Iv85kqJXWHQJ5475DNxOxlo9Ty5v.png",
    "satisfaction hd": "http://torrent-tv.ru/uploads/isdNgbfGENuaDPSMzsz8WMjBzc1rah.png",
    "дача": "http://torrent-tv.ru/uploads/mX1irJVUyLtrXr9vfDdhknRqiqV9wA.png",
    "правда тут": "http://torrent-tv.ru/uploads/6JMI68m3c7uK5DtCvF9HcmCl0R6tJy.png",
    "матч! футбол 3 hd": "http://torrent-tv.ru/uploads/OLHdmyfUev4mMX0OGniJrlUwHnMKOg.png",
    "матч! планета": "http://torrent-tv.ru/uploads/mWQ92sSmszzmjme9GTueLPCxagJGtl.png",
    "bridge tv": "http://torrent-tv.ru/uploads/dPhBiaViIznwjeWU3pTbIXFmS3iJkU.png",
    "конный мир hd": "http://torrent-tv.ru/uploads/q87VlmfaBeBhq8SOhAu0SVPEGjiqWM.png",
    "btv cinema": "http://torrent-tv.ru/uploads/0r004ZmoAtDSElNagVfiFjBZ5AetJT.png",
    "дождь hd": "http://torrent-tv.ru/uploads/381.png",
    "матч! наш спорт": "http://torrent-tv.ru/uploads/l0x8GopxrHL6jLiDGVHi8tIEc7RBt2.png",
    "нтв (+4)": "http://torrent-tv.ru/uploads/B5GA1cfgmn8EsxrdwfNUIrEbdqarXf.png",
    "gulli": "http://torrent-tv.ru/uploads/2IynBdmw3mmdXt01r8DXKxeor7STnw.png",
    "paramount comedy": "http://torrent-tv.ru/uploads/5EtvAWXB7VK1Yw82yvO28sY28dU4ZC.png",
    "родное кино": "http://torrent-tv.ru/uploads/y7saqicb538iqo64ho46hh46.png",
    "360 градусов hd": "http://torrent-tv.ru/uploads/K4tiqb5ajIgmxqh8X5moJuDjN7q5hx.png",
    "mi lady": "http://torrent-tv.ru/uploads/Fd556PD2ffD6zdVUiX0dvVfBJavBNd.png",
    "hd life": "http://torrent-tv.ru/uploads/jUteUS0xRGdvLyBVqNjowEUDkOjT0t.png",
    "hd fashion (sd)": "http://torrent-tv.ru/uploads/nEIXShrZ56g4IA4VKXReUBF32iYwKJ.png",
    "bbc world news": "http://torrent-tv.ru/uploads/8cSYWwvq6BAzcGDjJODvCGQYGJ2c4S.png",
    "первый канал (+8)": "http://torrent-tv.ru/uploads/lRjN5HOOX0txLz8nigpKqpVw5CBKJZ.png",
    "phoenix marie tv": "http://torrent-tv.ru/uploads/mC9hfoTbTEXlNXEVFrJvXaj78QGUhA.png",
    "москва доверие": "http://torrent-tv.ru/uploads/9oPazhJQrGZcSN64ZOS3WjLwGmQIZy.png",
    "motorsport": "http://torrent-tv.ru/uploads/7fAmhbXY4MwyRxACHpWPIaNqNiW6Y8.png",
    "мульт": "http://torrent-tv.ru/uploads/ZVzHvGF8mZ6RTsSh6aWsPbF1FBLjyp.png",
    "mtv rocks": "http://torrent-tv.ru/uploads/SEwn7rL2FxPcf5Ol9KRKedIwXlpsAP.png",
    "2x2 (+5)": "http://torrent-tv.ru/uploads/WMlvhNmhzmk2JgKct8Oa5FcWHmR7fZ.png",
    "jimjam": "http://torrent-tv.ru/uploads/BPDFCK5SQF3mXu5MsDNSdtvz4Gjawo.png",
    "russia today hd": "http://torrent-tv.ru/uploads/rL14fwCe8q10mKTchOwLkfwQVki9XK.png",
    "миллет": "http://torrent-tv.ru/uploads/zDsxAdZp80tZ43Rd2IWAgFOFFYDkwh.png",
    "мама": "http://torrent-tv.ru/uploads/nw9fROQIjjKSDp8Wjkjl1Wt0n0xHxd.png",
    "tiji": "http://torrent-tv.ru/uploads/mD3GW0E7rdPwc4stjk7xrLI2gZn4Hq.png",
    "viasat motor": "http://torrent-tv.ru/uploads/RuYtGxEpqJ5DG7WxGCMWNDXosRdh59.png",
    "первый канал hd": "http://torrent-tv.ru/uploads/VxAFWzh1y88c8Aqa17TsxD2IO5pqoi.png",
    "kronehit tv hd": "http://torrent-tv.ru/uploads/dq6m0UE9ffgAbXNt49qDlIAr7T8lud.png",
    "3s tv": "http://torrent-tv.ru/uploads/AL7uQOgsyYqE7V1BagxC2jqQVOvucp.png",
    "viasat nature-history hd": "http://torrent-tv.ru/uploads/pSP6zxmuO4PU6xa6KRlZ9L8vvVM2Dy.png",
    "стрк hd": "http://torrent-tv.ru/uploads/xOmVS1kQFIHeAwqtJbBfrbE75Quj2a.png",
    "эгоист тв": "http://torrent-tv.ru/uploads/moG8uExVh4nw3MN7dmGFdysJHBWLk6.png",
    "amc": "http://torrent-tv.ru/uploads/rozrC8ZPYA1YGajyow35doeVcaQzpa.png",
    "футбол": "http://torrent-tv.ru/uploads/472.png",
    "зоопарк": "http://torrent-tv.ru/uploads/1Ugpb5T1THFcFpn19Mnua21KxHkjct.png",
    "sky sports 2 hd": "http://torrent-tv.ru/uploads/B40l6w5yVEpOpZ31io1VzkubFnygLT.png",
    "disney channel (+2)": "http://torrent-tv.ru/uploads/awk1MeZ3IP1HOAtPt4jfvdR2P6YqIc.png",
    "amedia premium hd": "http://torrent-tv.ru/uploads/ornzQpk6WCW6xk0lyBhlwqH8u2QyU7.png",
    "интер+": "http://torrent-tv.ru/uploads/QEdaDBbqr13CCfwKQAP77UZYPQIPn0.png",
    "бобер": "http://torrent-tv.ru/uploads/2Edln8vEbg7UUSVUo7lIJPR780OWAR.png",
    "arirang tv": "http://torrent-tv.ru/uploads/ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png",
    "новый канал": "http://torrent-tv.ru/uploads/k7YdHhVpFZPIkBMXS2P2O2TkZSPf0y.png",
    "setanta sports + hd": "http://torrent-tv.ru/uploads/jW7pJhmebW2fZsXUTvDuRQLahgiLlU.png",
    "ржд тв": "http://torrent-tv.ru/uploads/qa6177IUBWR0hYt1HKXxlMrF5MStOb.png",
    "нтв": "http://torrent-tv.ru/uploads/B5GA1cfgmn8EsxrdwfNUIrEbdqarXf.png",
    "rtg tv": "http://torrent-tv.ru/uploads/IeaOjwR6Q9eJjGZr0LYk2tpchM3ITZ.png",
    "дом кино премиум hd": "http://torrent-tv.ru/uploads/uPO7sY6QsL94BV6QZGtLaxmPd75DJB.png",
    "нтв+ кинохит": "http://torrent-tv.ru/uploads/iQ0I0OnN11zzfQc5yivSJtXLiV0n8J.png",
    "zoom": "http://torrent-tv.ru/uploads/SyisYhg411o7z9kXci4vfpLq4KBZZ4.png",
    "история": "http://torrent-tv.ru/uploads/PNRaeOUFzOPFtrclFBBRTckj6Lvo0u.png",
    "брянская губерния": "http://torrent-tv.ru/uploads/V5M08NU3jRbd2wKvtVLIRbg9J6ObAZ.png",
    "tv safina": "http://torrent-tv.ru/uploads/mJUmNhJbQqcr2NPppAryEJqDPBJGV0.png",
    "dream tv": "http://torrent-tv.ru/uploads/3k3m3ElnUQ0UhX54qa7hOGbmNjKZSc.png",
    "world fashion hd": "http://torrent-tv.ru/uploads/2YI4sT9YkGezrw9vZPn0uIRhZ7E2BV.png",
    "sky sports 3 hd": "http://torrent-tv.ru/uploads/5Ft6qyJQXmV1MogsjpO79oKKruQj64.png",
    "sports tv": "http://torrent-tv.ru/uploads/ftwRrxmQfT8aJ7k5ej6e7UYzWdfsui.png",
    "canal+ futbol hd": "http://torrent-tv.ru/uploads/AnO4jFuPE8UbNyaJVjNHuTFfBrLRVg.png",
    "лдпр тв": "http://torrent-tv.ru/uploads/1keO0CoTmw0B3VZRe4TZnzfGdKDqSj.png",
    "mtv dance": "http://torrent-tv.ru/uploads/ZXKNRw6Ai8u4lY0wxeycQwj2dIkm66.png",
    "anyday 3d": "http://torrent-tv.ru/uploads/r8hT8FoPXteOKe9H8FjQTdIttfOg8S.png",
    "tv 1000": "http://torrent-tv.ru/uploads/WJMEvVafVakrm7BUMy1lzku7VQCx25.png",
    "zee tv": "http://torrent-tv.ru/uploads/1HooaeEhMSvpKmWv6nneZxnTmG5r6Q.png",
    "rtg hd": "http://torrent-tv.ru/uploads/g4MDyw0yqXWkIar8eH0cgCz4xhiKON.png",
    "bein sports 1 hd": "http://torrent-tv.ru/uploads/lqnLsL3LkmnVte1I8djXkbFEYFx91o.png",
    "ubr": "http://torrent-tv.ru/uploads/F6EzmjkOBVB0gmn1kQX6itv5VvFml5.png",
    "arena sport 3": "http://torrent-tv.ru/uploads/x31HEc9Vo87VdvF1eXQTl61ZXgq7HY.png",
    "animal planet": "http://torrent-tv.ru/uploads/45.png",
    "fox": "http://torrent-tv.ru/uploads/XGC77wQNeEyaJ2z2mDipyIPsoF0xc1.png",
    "retro music tv": "http://torrent-tv.ru/uploads/zVS9G1oine56udlAK30gNut16iJ9Ft.png",
    "hd кино": "http://torrent-tv.ru/uploads/iHVs7YvUVlUvMTnlma7GMpX5p0Tpy1.png",
    "матч! боец": "http://torrent-tv.ru/uploads/xj1tPp6g9LmQH5KAN0gFpWYoa9RdbL.png",
    "cnl": "http://torrent-tv.ru/uploads/wwQ6u4lFXyaUDJLu2JOh6mtbkIz0Nf.png",
    "первый канал (снг)": "http://torrent-tv.ru/uploads/WimZD6efLd6QotrPP9uiJeF7t50nFv.png",
    "новороссия тв": "http://torrent-tv.ru/uploads/zUchDq13UVJRmlwAl3feV8cgKHYSyE.png",
    "индия": "http://torrent-tv.ru/uploads/XVWyHt5bFFcZNzmysBSjuVdGBGl45D.png",
    "business": "http://torrent-tv.ru/uploads/wvwXc2x8Bjev90GD6LO6t7TL2aKW1h.png",
    "техно 24": "http://torrent-tv.ru/uploads/JbUGHLuuZa3WQbjtbzUo0cDZkGnLRK.png",
    "tv6": "http://torrent-tv.ru/uploads/l1UpPzlU6nnHGIAdtNGTgns5V2l6jV.png",
    "viasat sport baltic": "http://torrent-tv.ru/uploads/ZIITckvF1w5u1MlubmhoG45HxPgcZZ.png",
    "canal+ sport hd (france)": "http://torrent-tv.ru/uploads/I4vGNtOsYtkBnwOwFi94RHazK1ngqw.png",
    "tv1000 comedy": "http://torrent-tv.ru/uploads/Rg2qtCBJcy6nGCC0D3EjX4xl1Rn2kw.png",
    "eska best music tv hd": "http://torrent-tv.ru/uploads/wI3e672FQZpD8yr8aIV8Q2fL15zENv.png",
    "zik (украина)": "http://torrent-tv.ru/uploads/dB1PmpYtgeI0C4u7Cv1QoXHlvc4JtT.png",
    "pink o tv": "http://torrent-tv.ru/uploads/aI99kH6bHY5Qt2ph4W1Nh0wxdzd1p8.png",
    "тонус тв": "http://torrent-tv.ru/uploads/bE8WfReOerYTIbqPOo6VD2ajrFdOBT.png",
    "здоровое тв": "http://torrent-tv.ru/uploads/2LgJcyMnjJpMAhUqX3rdQ4ChOmbuTo.png",
    "tgirls tv": "http://torrent-tv.ru/uploads/FufZ2heFswzvAbRkTQZs8UJBYGsxuG.png",
    "eurosport 1 hd": "http://torrent-tv.ru/uploads/DpFTzUEA3y67Z6ObTPF4xH0XLNRAZm.png",
    "планета": "http://torrent-tv.ru/uploads/o7wnxC58C4KfCnX0hh0il0LTRlPfSg.png",
    "живи": "http://torrent-tv.ru/uploads/cOluSjslxxs3JZtSVO8c15xh7h8SDU.png",
    "карапуз тв hd": "http://torrent-tv.ru/uploads/ieXzw5xeahW3OoO66m2LX8GwLCYyYl.png",
    "1 hd": "http://torrent-tv.ru/uploads/FtLnmUwjG18XJFEKYvLKjwUq1gwHVZ.png",
    "беларусь 24": "http://torrent-tv.ru/uploads/GxA1KJP5YwpWc38BoPEmLwQH6uDeEz.png",
    "2x2": "http://torrent-tv.ru/uploads/hTpJUV15GSTxZ5kJQGLcn42kCzKyEH.png",
    "интерра тв": "http://torrent-tv.ru/uploads/Akn9ntxqkSNrX3BTFRRtXPaEYBszjR.png",
    "томское время": "http://torrent-tv.ru/uploads/1Z7yLtfyuITQhXchO59gwyQ3mES7qS.png",
    "первый канал (+4) (4:3)": "http://torrent-tv.ru/uploads/nHJycH0CkOhPeZ9DmB47iSMWP5HyWz.png",
    "tv bakhoristan": "http://torrent-tv.ru/uploads/LoXaN929SQC5r5aQ3JETDXwG6VlPMk.png",
    "tv-5": "http://torrent-tv.ru/uploads/iPHeoajUJttv5qZl2yfcOYB1qFx6nv.png",
    "ржд тв hd": "http://torrent-tv.ru/uploads/qa6177IUBWR0hYt1HKXxlMrF5MStOb.png",
    "fоx hd": "http://torrent-tv.ru/uploads/Pl8S60EJ52htHxi1gAw1SS1y8i1p3z.png",
    "sport 1 cz": "http://torrent-tv.ru/uploads/kCLlfkFz3Ba3BL9Jc9ZPgUKXh2piyv.png",
    "24 док": "http://torrent-tv.ru/uploads/H1UXBai10DjYfScfv1sNAILV9EPDer.png",
    "djing underground hd": "http://torrent-tv.ru/uploads/ceUcUA6hsEV7tBVmSF1chE203B14M3.png",
    "setanta sports eurasia hd": "http://torrent-tv.ru/uploads/1wgHdJP76TCItF14FxDwBtak8tmxRv.png",
    "djing animation hd": "http://torrent-tv.ru/uploads/ZA8pwcclRpzTflNKLqeZmDHCA7lHoX.png",
    "tv1000 comedy hd": "http://torrent-tv.ru/uploads/ygGiR2hkQLySH6khdo8GV9CyMJ8dXi.png",
    "fap tv gay": "http://torrent-tv.ru/uploads/vJB3tfzXuDX8R7eLXV63tCFgxnOgP1.png",
    "fashion tv": "http://torrent-tv.ru/uploads/PSjqabjhYIBqcS8hUA8WNrZEjV4zZY.png",
    "открытый hd": "http://torrent-tv.ru/uploads/CdIvMNsa7gAihJnpAKX8QnMdpvhAXc.png",
    "вместе рф": "http://torrent-tv.ru/uploads/qa50GYekwBWym7KtoJdzrWHWqN8TeU.png",
    "sport 1 lt": "http://torrent-tv.ru/uploads/nRFc87aOV1vRnjEqmQZUneZe4HiCqn.png",
    "нло тв": "http://torrent-tv.ru/uploads/2VGhYruaQo19G1NLGoOiTrwmPxef7d.png",
    "страна": "http://torrent-tv.ru/uploads/5G27bahViND43dD1VlkaKlQRsYOqwL.png",
    "бокс тв": "http://torrent-tv.ru/uploads/s3qlrVrIjISf7K0G4HHRYw5rmAej4b.png",
    "стс (+1)": "http://torrent-tv.ru/uploads/tPa64bmSSwAqcmgolRpPiJr3MA3XIc.png",
    "redlight hd": "http://torrent-tv.ru/uploads/5tFZcJtKAZRbXtKGDuLe8FZ3lK9LI5.png",
    "food network hd": "http://torrent-tv.ru/uploads/V1JsTAyNxWeXbkKyqDmtOAt8YptBYl.png",
    "белсат тв": "http://torrent-tv.ru/uploads/9VYuUQxx1ss7ieu2upENtlibyamBP0.png",
    "первый канал (+2)": "http://torrent-tv.ru/uploads/Lo2zy8h0msIieULsbHOjV1oSInHogr.png",
    "семейное hd": "http://torrent-tv.ru/uploads/ORgdUno4IvNQYiShiEY4srF16JguLs.png",
    "нтв (+7)": "http://torrent-tv.ru/uploads/B5GA1cfgmn8EsxrdwfNUIrEbdqarXf.png",
    "top shop": "http://torrent-tv.ru/uploads/uD257Lhw7Ko2YD1reC0nRqW7lpy93D.png",
    "sport 2 cz": "http://torrent-tv.ru/uploads/YLmEjnczWQGJcZC0SxRcH4ifPcwYlx.png",
    "горящий камин hd": "http://torrent-tv.ru/uploads/ujkL8d4MnAfrWSOBme8UxGFq6AJodT.png",
    "м2": "http://torrent-tv.ru/uploads/U4s78hznNz7mFYZQICkxN7J0HTtlCP.png",
    "м1": "http://torrent-tv.ru/uploads/ezvu2ugYMGnZ968LlnjPw7VjqWIPeM.png",
    "мир hd": "http://torrent-tv.ru/uploads/Oq6h2IicTagHENQu1mFkjLk5rChMnr.png",
    "горизонт тв": "http://torrent-tv.ru/uploads/o7wnxC58C4KfCnX0hh0il0LTRlPfSg.png",
    "tv1000 premium hd": "http://torrent-tv.ru/uploads/raoDrpin8VKmi522LZWzSF0fLRO04m.png",
    "пятница (+2)": "http://torrent-tv.ru/uploads/0fafj6PSIWdqtBdgwYTl9M06SDU2wA.png",
    "отр": "http://torrent-tv.ru/uploads/CqxKorK72v3ULbWkB3ZOhdte0duYZa.png",
    "купи дом тв hd": "http://torrent-tv.ru/uploads/7CyfedwVltdaMcZXD3Xx7wa50mZJom.png",
    "super tv": "http://torrent-tv.ru/uploads/iRrgl4xiCvibdxWfiQcVUWuYCYCI9K.png",
    "звезда (+2)": "http://torrent-tv.ru/uploads/wa6skHc8W2MRz9Mm3qoKS4LpctSvYs.png",
    "viasat nature east": "http://torrent-tv.ru/uploads/yimDcPvajJcUKQm9bY15cDdp3rJFcp.png",
    "dobro tv": "http://torrent-tv.ru/uploads/tcHbtjkY9gYD4VqipgwLP2BYxgdrZb.png",
    "ника тв": "http://torrent-tv.ru/uploads/pb3d3rBN4qW7ggzsosbAZXflfIv0Ty.png",
    "телепутешествия": "http://torrent-tv.ru/uploads/fz4bqwLySJAQkUN7l2EPKNqyvilfRD.png",
    "домашний": "http://torrent-tv.ru/uploads/qmqrH2E2EX11qitbIvq0CYsxQjsHGm.png",
    "8 канал": "http://torrent-tv.ru/uploads/wKPUJjcpZIfI5zBSZwNayOlv63zRNV.png",
    "boomerang": "http://torrent-tv.ru/uploads/tsP2U3zkp5o8B0TD6luRLg0leS9FvM.png",
    "планета hd": "http://torrent-tv.ru/uploads/1QjirpCLi3q9qPu1CTvEvCB0BfINeo.png",
    "кто есть кто": "http://torrent-tv.ru/uploads/MwNkO3fXd6KefRdiGlOdOQ5q0Zu7kS.png",
    "сонце": "http://torrent-tv.ru/uploads/TJXJVeoBFRMFrUgzpPW4dunJL6XSzn.png",
    "cbc": "http://torrent-tv.ru/uploads/GuGWslWHNQ2fb88q6JYKSAV1n9A6hF.png",
    "нтв hd": "http://torrent-tv.ru/uploads/zdJ3ye6d3UWl5a56zm6LjqYH6ziSOs.png",
    "надежда": "http://torrent-tv.ru/uploads/fvCkzRJPsTx4HONWPv3vPMjQNloPBT.png",
    "россия к (+2)": "http://torrent-tv.ru/uploads/rVrDeCUhT4RPKIa2h9qRtnDon3Pd9X.png",
    "бигуди": "http://torrent-tv.ru/uploads/JvcMdB5e6KVBpbXT12ulzmDqenheRx.png",
    "кот тв": "http://torrent-tv.ru/uploads/Rtdtc632nbBQ2TsymgXhkOt7nhytjW.png",
    "teletravel hd": "http://torrent-tv.ru/uploads/4ZlASq3oDpOjXfhwluOzY74sy9elaE.png",
    "русский детектив": "http://torrent-tv.ru/uploads/7I7VjbsFMIkZdoSbHFXiKEVZKNUbOM.png",
    "history channel": "http://torrent-tv.ru/uploads/9cVifexiWW0qWDhhpnLNVydoZkeRqZ.png",
    "passionxxx": "http://torrent-tv.ru/uploads/U2oO3j1eda31nrTwHqaQ8psrLfH5CD.png",
    "пятый канал": "http://torrent-tv.ru/uploads/nIUDYY41OO4Xo0ntGpGv2rfpOR5ngt.png",
    "ямал регион": "http://torrent-tv.ru/uploads/xapccCaMjlT6JEAkZmk27wzCXlEU2m.png",
    "kazsport": "http://torrent-tv.ru/uploads/Hrl1mL3UFqhv8OE7z0wbo4Z0zR6Knc.png",
    "оплот 2": "http://torrent-tv.ru/uploads/EqwpuUgrI6Wl6JVDK2fLtXkNaqOXeU.png",
    "fox crime": "http://torrent-tv.ru/uploads/uuLatFz2xaQlUZ0UyZwt7UukKq2Ikg.png",
    "mtv hits": "http://torrent-tv.ru/uploads/iLJhuLh9kFLQkG4ERvLGSjSgMfNiM4.png",
    "шансон тв": "http://torrent-tv.ru/uploads/VY0TyCCkKOj5b8BhBJjT020sQoxL9F.png",
    "тнв-татарстан": "http://torrent-tv.ru/uploads/kMdYm3qFLgK52EV0ymvRBB43peSrj9.png",
    "рен тв (+3)": "http://torrent-tv.ru/uploads/LJvkfB2kYaDzij1Y13Fy6syUCkP5Y6.png",
    "french lover tv": "http://torrent-tv.ru/uploads/XHZQcVegBeqVMOYDqzr9EruPgbQpX0.png",
    "онт беларусь": "http://torrent-tv.ru/uploads/a84If8XdqSFa6nHpegdujt52vAGNJW.png",
    "домашний магазин": "http://torrent-tv.ru/uploads/yhzajV7vdLogQzMKat0rLJWaDkPpTP.png",
    "2+2": "http://torrent-tv.ru/uploads/XHXBC3ghvhh100BNXylSgJLx5FVQgD.png",
    "gamanoid hd": "http://torrent-tv.ru/uploads/DxEQkipHmJjSY0wHGKHDV6eAZKiwoG.png",
    "нтв мир": "http://torrent-tv.ru/uploads/ykpU49Gl1akVkgiVSsCm5B4TjXvQ64.png",
    "id xtra": "http://torrent-tv.ru/uploads/fq3ovkZeu4R4YVYt1VMZN1NU7mMrH9.png",
    "o-tv": "http://torrent-tv.ru/uploads/UlIt4rE3FZs7IQmPN3tsGS6fqY5F1D.png",
    "россия 1 (+4)": "http://torrent-tv.ru/uploads/DL17FIS3R8m6eWTwFvdDYualmxvkGV.png",
    "cnn international": "http://torrent-tv.ru/uploads/lIwbRbM3ve4ixhFXp75Oap9nzcO71G.png",
    "discovery science": "http://torrent-tv.ru/uploads/GAaO3EfDwMuHAIelG4gYW6TDEYbLnS.png",
    "унiан": "http://torrent-tv.ru/uploads/fhpFrTDoI9xx7UlK65KAjAbdTGehLL.png",
    "etv 2 (эстония)": "http://torrent-tv.ru/uploads/HExQnCel4LeRvVFpvXj7hXfMXslkGE.png",
    "viasat fotboll": "http://torrent-tv.ru/uploads/0JLqj3qwFoT1Y61scCyUdWioV5U6hx.png",
    "jasmin tv": "http://torrent-tv.ru/uploads/MBRUFcRx5wtHLZmgahvcGdXB2ERdst.png",
    "нтв+ премьера": "http://torrent-tv.ru/uploads/lDiI54Y3LjIAOg5VV0adicP3OJrdgo.png",
    "wbc hd": "http://torrent-tv.ru/uploads/fMdJvc8moH4HGH5OYqsZwskCowQYuE.png",
    "нтв (резерв)": "http://torrent-tv.ru/uploads/B5GA1cfgmn8EsxrdwfNUIrEbdqarXf.png",
    "trt haber hd": "http://torrent-tv.ru/uploads/c8LtPc7MolLEoibMHNLYdhYxk075l0.png",
    "рада украина": "http://torrent-tv.ru/uploads/hBFJBYNiqZUom0ooVtNEJKliZwfioO.png",
    "bbc 2 hd": "http://torrent-tv.ru/uploads/XX6FaI7Y7GTAIdaSLFvSzgl99Bfk9J.png",
    "eska oldscool tv hd": "http://torrent-tv.ru/uploads/7LW3s6C3D3yeciqTY0CKXpEmL3Tb3w.png",
    "рбк": "http://torrent-tv.ru/uploads/JUMDXZxxB3UiVpMpU8t0aCpbVzxTmP.png",
    "теледом hd": "http://torrent-tv.ru/uploads/XviuCfRo0T4WFTOhFaC978AwZ1a3Ge.png",
    "43 канал hd": "http://torrent-tv.ru/uploads/1mNoU1QXmcmK48eVTlnADtsEBmA2sN.png"
}
